### PR TITLE
Always enable file based user auth

### LINKED ISSUE #1629: file (and native?) realm must always be enabled.
## Bug Report
**What did you do?**

Enabled SAML realm. I believe this implicitly disables the default native and file realms.

**What did you expect to see?**

The cluster should come back online normally after I enable SAML.

**What did you see instead? Under which circumstances?**

The cluster attempted to push a new config, but ultimately failed:

* readinessProbe failed: 

```
{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [elastic-internal-probe] for REST request [/]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"unable to authenticate user [elastic-internal-probe] for REST request [/]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}
```

* operator failed reconcilation due to access problems:

```
{"level":"error","ts":1566800177.9562502,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"elasticsearch-controller","request":"default/grey-sector","error":"error during migrate data: 401 Unauthorized: unable to authenticate user [elastic-internal] for REST request [/_cluster/settings]","errorCauses":[{"error":"error during migrate data: 401 Unauthorized: unknown","errorVerbose":"401 Unauthorized: unknown\nerror during migrate data\ngithub.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile...
```

**Environment**

* ECK version: 0.9.0

* Kubernetes information: GKE, 1.12.8-gke.10

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
...
spec:
  version: 7.3.0
  nodes:
  - nodeCount: 3
    config:
      ...
      xpack.security.authc.realms.saml:
        cloud-saml:
           # ... saml config here 
```

### PR DESCRIPTION
**Pull request by thbkrkr**
The operator relies on file realm for creating all the internal users
including the built-in elastic user. This commit makes sure the file
realm is always enabled in case a user wants to configure additional
realms.
The order of the file realm is set to -100 to favor the fact that it is
used first but there is no complete guarantee about that. The user can
still configure a realm with an order less than -100 but it is very
unlikely given this is not suggested in the documentation (order starts to 0).
The main known issue could be to configure a realm that relies on a
system (e.g. Active Directory) that has a temporary lock-out period
after several successive failed login attempts, as being checked first
(https://www.elastic.co/guide/en/elastic-stack-overview/current/trouble-shoot-active-directory.html).

Resolves #1629.

### CODE REVIEW

File: pkg/controller/elasticsearch/settings/fields.go [hunk 1]
```diff
@@ -19,6 +19,7 @@ const (
 	PathData = "path.data"
 	PathLogs = "path.logs"
 
+	XPackSecurityAuthcRealmsFileFile1Order          = "xpack.security.authc.realms.file.file1.order"
```
Comment (charith-elastic) [inline pkg/controller/elasticsearch/settings/fields.go]: I am a bit confused by this because my understanding of the [documentation](https://www.elastic.co/guide/en/elastic-stack-overview/current/realm-chains.html) suggests that this should look like the following:

```
xpack.security.authc.realms.file1.type = file
xpack.security.authc.realms.file1.order = -100
```

I see from the issue that Jordan's working configuration looks like what you have here, so I am probably mistaken. I just wanted to point it out just in case.

Comment (thbkrkr) [reply pkg/controller/elasticsearch/settings/fields.go]: Good point! I'm using the syntax introduced in [7.x](30241) that will not work in 6.8 and which is a [breaking change](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#include-realm-type-in-setting).

I'm going to support the 2 different syntaxes given the version.

**Comment by sebgl** [comment]
> I'm mixed to use a more advanced way to switch the config for this little variation, like we did in the past for ES and still have for Kibana.

I think I tend to prefer what you implemented where we pass the version around and use it where it matters, instead of having several driver plugs.
