### PR TITLE
Set basePath in Metricbeat when using stack monitoring

### LINKED ISSUE #8310: ECK Stack Monitoring does not work when server.basePath is defined on Kibana
When the Kibana is deployed with ECK using the `server.basePath` option and the `server.rewriteBasePath` set as `true`, the [ECK Stack Monitoring](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-stack-monitoring.html) is not able to collect the Kibana metrics, as it does not propagate the value of the `server.basePath` parameter to the Kibana endpoint defined on the sidecar Metricbeat container.

Example Kibana config:
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-quickstart
  namespace: eck
spec:
  version: 8.15.0
  count: 1
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: quickstart
  elasticsearchRef:
    name: quickstart
  config:
    monitoring.ui.ccs.enabled: false
    server.basePath: /test
    server.rewriteBasePath: true

  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: "/test/login"
              port: 5601
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: eck
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  rules:
    - host: kibana.test.local
      http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: kibana-quickstart-kb-http
                port:
                  number: 5601
```

Example of Metricbeat config Secret created by the ECK Operator (evidence that it did not propagate the base path):

```
metricbeat:
    modules:
        - hosts:
            - http://localhost:5601
          metricsets:
            - stats
            - status
          module: kibana
          password: 48hNR28L47VhxP714IPDX8vk
          period: 10s
          ssl:
            enabled: false
            verification_mode: certificate
          username: elastic-internal-monitoring
          xpack:
            enabled: true
output:
    elasticsearch:
        hosts:
            - https://quickstart-es-http.eck.svc:9200
        password: 160W19mTgXVu6x712n6sqyQP
        ssl:
            certificate_authorities:
                - /mnt/elastic-internal/kb-monitoring-association/eck/quickstart/certs/ca.crt
            verification_mode: certificate
        username: eck-kibana-quickstart-eck-quickstart-beat-kb-mon-user
processors:
    - add_cloud_metadata: null
    - add_host_metadata: null

```

When looking at the Metricbeat container logs, the following messages can be found:

```
{"log.level":"error","@timestamp":"2024-12-10T14:37:07.206Z","log.origin":{"function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).fetch","file.name":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset kibana.node_rules: HTTP error 404 in : 404 Not Found","service.name":"metricbeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-12-10T14:37:07.648Z","log.origin":{"function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).fetch","file.name":"module/wrapper.go","file.line":256},"
```

Even with the following [PR](https://github.com/elastic/cloud-on-k8s/pull/8053) and ECK Operator in version 2.15.0, the problem still persists.

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #8310

### CODE REVIEW

**Comment by pebrc** [comment]
buildkite test this -f t=Test*StackMonitoring* -m s=7.17.25,s=8.15.4

**Comment by pebrc** [comment]
buildkite test this -f t=Test.*StackMonitoring -m s=7.17.25,s=8.15.4

**Comment by pebrc** [comment]
buildkite test this -f p=gke,t=Test.*StackMonitoring -m s=8.16.0,s=7.17.25,s=8.15.4

File: pkg/controller/common/stackmon/sidecar.go [hunk 1]
```diff
@@ -29,6 +29,7 @@ func NewMetricBeatSidecar(
 	baseConfigTemplate string,
 	namer name.Namer,
 	url string,
+	basePath string,
```
Comment (thbkrkr) [inline pkg/controller/common/stackmon/sidecar.go:32]: `NewMetricBeatSidecar(..)` and `buildMetricbeatBaseConfig(..)` start to have a lot of parameters. At some point, it might be reasonable to introduce a struct?

**Review by thbkrkr — APPROVED** [review]
Looks good 👌

File: pkg/controller/common/stackmon/sidecar.go (hunk 1 above)
Comment (pebrc) [reply pkg/controller/common/stackmon/sidecar.go:32]: I think fundamentally basePath should not be in the common stack monitoring code. But I wanted a quick fix we could include in the release. Ideally one would want a bit more more modular code where we can have application/module specific settings in the specific controllers.

**Comment by pebrc** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|2.16|[](https://github.com/elastic/cloud-on-k8s/pull/8315)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
