### PR TITLE
Perform StatefulSets deletions before replicas downscale

### LINKED ISSUE #2009: Bypass downscale checks to remove StatefulSets with 0 replicas
Following a discussion with @charith-elastic and @david-kow.

The `TestMutationMDIToDedicated` E2E test is failing since we introduced better E2E tests with https://github.com/elastic/cloud-on-k8s/pull/1949.

This test is supposed to create 2 new StatefulSets (master, data), and remove the old one (master + data).
It stays stuck with the old master+data StatefulSets with 0 replicas never deleted.

This is because we have a check in the downscale implementation that skips downscale if we're about to remove the last master node. In this particular case, there is only one master node (the new dedicated master), so the algorithm refuses to downscale a StatefulSet of master nodes. But this StatefulSet has 0 replicas!

I think we can move the StatefulSet removal much higher in the downscale logic, before we do any safety check. If an actual (not expected) StatefulSet has 0 replicas, it means:

* it has previously been slowly downscaled by us to 0 replicas, with data migration when removing nodes
* it does not currently have any pod running (checked by expectations)
* if the user themselves has set the nodeSet count to 0, we go through the same slow downscale with data migration as above - in the operator world a nodeSet with a count of 0 should be handled the same as no nodeSet at all

We discussed how a nodeSet with a count of 0 could eventually mean "I want to pause this StatefulSet, please keep the data volumes around", but that's not something we should fix right now. And it generally needs more thinking to implement this feature.

### PR DESCRIPTION
**Pull request by sebgl**
We had a bug where a StatefulSet with 0 replicas could be kept forever
under particular conditions (eg. cannot be removed since there is a risk
to remove the last master node... even though there is 0 replicas).

This commit fixes it by decoupling StatefulSets deletions from
StatefulSet downscales.
A StatefulSet deletion is only performed when the actual StatefulSet has
0 replicas. Our expectations mechanism ensures there is no Pod still
alive for that StatefulSet (eg. if it was just downscaled from 1 to 0
replicas). So that StatefulSet can be safely garbage-collected.

StatefulSets deletions are now ran before handling downscales,
regardless of any downscale invariant constraint.
The downscale code is a bit simplified since it does not need to handle
StatefulSets deletions anymore.

Fixes #2009 and the TestMutationMdiToDedicated E2E test.

### CODE REVIEW

File: pkg/controller/elasticsearch/driver/downscale_test.go [hunk 1]
```diff
@@ -969,3 +992,51 @@ func Test_removeStatefulSetResources(t *testing.T) {
...
+				sset.TestSset{Namespace: "ns", Name: "sset3", ClusterName: es.Name}.Build(),
+			},
+			objs: []runtime.Object{
+				sset.TestSset{Namespace: "ns", Name: "sset1", ClusterName: es.Name}.BuildPtr(),
+				sset.TestSset{Namespace: "ns", Name: "sset2", ClusterName: es.Name}.BuildPtr(),
+				sset.TestSset{Namespace: "ns", Name: "sset3", ClusterName: es.Name}.BuildPtr(),
+			},
+			wantRemaining: sset.StatefulSetList{
+				sset.TestSset{Namespace: "ns", Name: "sset2", ClusterName: es.Name}.Build(),
+			},
```
Comment (david-kow) [inline pkg/controller/elasticsearch/driver/downscale_test.go]: add a case with sset already removed?
