### PR TITLE
Add linter config and fix simple lint warnings

### LINKED ISSUE #1109: Run golangici-lint during CI
Linter (golangci-lint) should be enabled and configured so that new builds don't fail on current lint errors.

### PR DESCRIPTION
**Pull request by charith-elastic**
- Adds a configuration file for running `golangci-lint` on the operators source tree.
- Fixes "simple" (i.e. unlikely to cause any disruptions) lint warnings.

Fixes #1109

### CODE REVIEW

**Comment by artemnikitin** [comment]
> Fixes #1109

Original issue mentioned running linters on CI but in PR I didn't saw changes to CI side. Are you planning to work on them too?

**Comment by charith-elastic** [comment]
Yes, this is just a draft PR so that people can see the changes I have made to the code so far. 
My plan is to fix the code and come up with an acceptable linter configuration first. Then I will update the CI configuration to run the linter automatically.

File: operators/pkg/controller/elasticsearch/keystore/config.go [hunk 1]
```diff
@@ -119,32 +118,32 @@ func NewConfigFromFlags() (Config, error, string) {
 		pass := viper.GetString(esPasswordFlag)
 
 		if user == "" {
-			return Config{}, errors.New("user is empty"), "invalid user"
+			return Config{}, errors.New("invalid user")
```
Comment (thbkrkr) [inline operators/pkg/controller/elasticsearch/keystore/config.go]: I think we are losing a little information here. Why is the user invalid?
I would tend to keep only `errors.New ("user is empty")`.

File: operators/pkg/controller/elasticsearch/keystore/config.go [hunk 2]
```diff
@@ -119,32 +118,32 @@ func NewConfigFromFlags() (Config, error, string) {
...
 			if err != nil {
-				return Config{}, err, fmt.Sprintf("password file %s could not be read", passwordFile)
+				return Config{}, errors.Wrapf(err, "password file %s could not be read", passwordFile)
 			}
 			pass = string(bytes)
 		}
 
 		if pass == "" {
-			return Config{}, errors.New("password is empty"), "invalid password"
+			return Config{}, errors.New("invalid password")
```
Comment (thbkrkr) [inline operators/pkg/controller/elasticsearch/keystore/config.go]: Same as the empty user: `errors.New ("password is empty").`?

File: operators/pkg/controller/elasticsearch/keystore/config.go (hunk 1 above)
Comment (charith-elastic) [reply operators/pkg/controller/elasticsearch/keystore/config.go]: Previously, the `reason` field of the log message would have said "invalid user" which is what I tried to preserve. But I agree that it would be better to explain why the user is invalid.

File: operators/pkg/controller/apmserver/config/config.go [hunk 3]
```diff
@@ -101,5 +101,9 @@ func NewConfigFromSpec(c k8s.Client, as v1alpha1.ApmServer) (*settings.Canonical
 		),
 		userSettings,
 	)
+
+	if err != nil {
+		return nil, err
+	}
```
Comment (thbkrkr) [inline operators/pkg/controller/apmserver/config/config.go]: Nitpick: Most of the time we prefer to stick the "check and return error block" to the previous block without a separated blank line. Quite often we use a blank line above the `return` but I think that's up to you. I think that can increase readability a little, especially when the functions reach more than 30 lines.

File: operators/pkg/webhook/server.go [hunk 4]
```diff
@@ -47,6 +47,10 @@ func RegisterValidations(mgr manager.Manager, params Parameters) error {
 		WithManager(mgr).
 		Build()
 
+	if err != nil {
+		return err
+	}
```
Comment (thbkrkr) [inline operators/pkg/webhook/server.go]: Same comment: stick this block to the previous one?

**Comment by charith-elastic** [comment]
retest this please
