### PR TITLE
fix: race condition for pre-existing StackConfigPolicy

### LINKED ISSUE #8912: StackConfigPolicy might not apply immediately on new clusters
The StackPolicy controller [waits for the Elasticsearch controller to first create the file settings Secret](https://github.com/elastic/cloud-on-k8s/blob/656cdf09d521c4f6bdc13865d85939eccee3b550/pkg/controller/stackconfigpolicy/controller.go#L306-L315):

```golang
		// the file Settings Secret must exist, if not it will be created empty by the ES controller
		var actualSettingsSecret corev1.Secret
		err = r.Client.Get(ctx, types.NamespacedName{Namespace: es.Namespace, Name: esv1.FileSettingsSecretName(es.Name)}, &actualSettingsSecret)
		if err != nil && apierrors.IsNotFound(err) {
			// requeue if the Secret has not been created yet
			return results.WithRequeue(defaultRequeue), status
		}
		if err != nil {
			return results.WithError(err), status
		}
```

If the Elasticsearch controller creates the Secret after the first StackPolicy controller iteration, or after the empty Secret is reflected in the client's cache, then the StackPolicy controller is going to wait `30 seconds`:

```golang
var (
	// defaultRequeue is the default requeue interval for this controller. It is longer than the default interval used elsewhere to account
	// for secret propagation times and the time it takes for Elasticsearch to observe the updates.
	defaultRequeue = 30 * time.Second
)
```

This gives enough time for the Elasticsearch pods to start without the stack config policies in place.

Other situations, like cache lags, Secret propagation issues, can lead to the same behaviour.

A fix is to fully reconcile that Secret  (including the creation of the empty Secret depending on the license)  in the StackPolicy controller.

### PR DESCRIPTION
**Pull request by pkoutsovasilis**
## Summary

  Reduces the time window where Elasticsearch clusters start with empty file-settings when a pre-existing
  StackConfigPolicy should be applied, by coordinating reconciliation between ES and SCP controllers.

## Problem

  **Prior to this PR:**
  1. User creates a StackConfigPolicy that targets ES clusters
  2. User creates an Elasticsearch cluster matching the SCP resource selector
  3. ES controller reconciles first and creates an empty file-settings secret
  4. ES cluster starts and runs with empty file-settings
  5. SCP controller eventually reconciles and updates the file-settings secret with policy configurations
  6. ES cluster must reload/restart to apply the policy settings

  This creates a non-negligible time window where the ES cluster operates without the intended policy configurations,
  even though the policy existed before the cluster was created.

 ## Solution

  The Elasticsearch controller now coordinates with the StackConfigPolicy controller to ensure policy settings are
  applied from the start when pre-existing policies target a new ES cluster.

  ### New Reconciliation Flow

  **When enterprise features are disabled:**
  - ES controller creates an empty file-settings secret immediately (no change)

  **When enterprise features are enabled:**

  1. **ES controller checks for targeting policies:**
     - Lists all StackConfigPolicies in the cluster
     - Checks if any policy targets this ES cluster

  2. **If a pre-existing policy targets the cluster:**
     - ES controller defers file-settings secret creation to the SCP controller
     - Returns re-queue to check again later
     - **Result:** SCP controller creates the secret with policy settings applied from the start

  3. **If no policy targets the cluster:**
     - ES controller creates an empty file-settings secret as before

 ## Testing

  - Unit tests coverage for policy targeting scenarios
    - Verify requeue behaviour when policies target ES clusters
    - Confirm empty secret creation when no policies exist
  - Manual testing with pre-existing StackConfigPolicies confirmed policy applied at cluster creation

### CODE REVIEW

**Comment by prodsecmachine** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/b045f3e6-456a-4167-891c-11dc2c4eb246?refs=f93a901cc88b6bace4aec2fe66f7f84a121b1a1a&source=prChecksComment) |
| :white_check_mark: | Licenses| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/b045f3e6-456a-4167-891c-11dc2c4eb246/license?refs=f93a901cc88b6bace4aec2fe66f7f84a121b1a1a&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

File: pkg/controller/stackconfigpolicy/stackconfigpolicy.go [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+	selector, err := metav1.LabelSelectorAsSelector(&policy.Spec.ResourceSelector)
+	if err != nil {
+		// Return error if the label selector syntax is invalid (e.g., malformed expressions)
+		return false, err
+	}
+
+	// Check namespace restrictions; the policy must be in operator namespace or same namespace as the target object.
+	// This enforces the scoping rules: policies in the operator namespace are global,
+	// policies in other namespaces can only target resources in their own namespace.
+	if policy.Namespace != operatorNamespace && policy.Namespace != obj.GetNamespace() {
```
Comment (pebrc) [inline pkg/controller/stackconfigpolicy/stackconfigpolicy.go:23]: Should the computationaly cheapest operation come first in the function i.e. move this to the top?

File: pkg/controller/stackconfigpolicy/stackconfigpolicy.go [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+// A policy targets an object if both following conditions are met:
+// 1. The policy is in either the operator namespace or the same namespace as the object
+// 2. The policy's label selector matches the object's labels
+// Returns true if the policy targets the object, false otherwise, and an error if the label selector is invalid.
+func DoesPolicyMatchObject(policy *policyv1alpha1.StackConfigPolicy, obj metav1.Object, operatorNamespace string) (bool, error) {
+	// Convert the label selector from the policy spec into a labels.Selector that can be used for matching
+	selector, err := metav1.LabelSelectorAsSelector(&policy.Spec.ResourceSelector)
+	if err != nil {
+		// Return error if the label selector syntax is invalid (e.g., malformed expressions)
+		return false, err
```
Comment (pebrc) [inline pkg/controller/stackconfigpolicy/stackconfigpolicy.go]: This error path will block ES reconciliation if any SCP in the cluster has an invalid label selector, even if it doesn't target the ES cluster where we call this method.

Can we maybe just log the error and move on?

File: pkg/controller/elasticsearch/driver/driver.go [hunk 3]
```diff
@@ -417,6 +420,52 @@ func (d *defaultDriver) Reconcile(ctx context.Context) *reconciler.Results {
 	return results.WithResults(d.reconcileNodeSpecs(ctx, esReachable, esClient, d.ReconcileState, *resourcesState, keystoreResources, meta))
 }
 
+// maybeReconcileEmptyFileSettingsSecret reconciles an empty file-settings secret for this ES cluster
+// based on license status and StackConfigPolicy targeting. When enterprise features are disabled always
+// creates an empty file-settings secret. When enterprise features are enabled and at least one StackConfigPolicy
+// targets this cluster returns true to requeue and doesn't create the empty file-settings secret. If no
+// StackConfigPolicy targets this cluster it creates an empty file-settings secret. Note: This logic here prevents
+// the race condition described in https://github.com/elastic/cloud-on-k8s/issues/8912.
+func maybeReconcileEmptyFileSettingsSecret(ctx context.Context, c k8s.Client, lcnChecker commonlicense.Checker, es *esv1.Elasticsearch, operatorNamespace string) (bool, error) {
```
Comment (pebrc) [inline pkg/controller/elasticsearch/driver/driver.go]:
```suggestion
func maybeReconcileEmptyFileSettingsSecret(ctx context.Context, c k8s.Client, licenseChecker commonlicense.Checker, es *esv1.Elasticsearch, operatorNamespace string) (bool, error) {
```

or  `licChecker`

File: pkg/controller/stackconfigpolicy/controller.go [hunk 4]
```diff
@@ -303,14 +303,13 @@ func (r *ReconcileStackConfigPolicy) reconcileElasticsearchResources(ctx context
 			continue
 		}
 
-		// the file Settings Secret must exist, if not it will be created empty by the ES controller
+		// Get the file settings secret. If it doesn't exist, we'll create it ourselves.
+		// Previously, we would requeue waiting for the ES controller to create it,
+		// but this caused a race condition (see https://github.com/elastic/cloud-on-k8s/issues/8912).
+		// Now the StackConfigPolicy controller takes full ownership of creating this secret.
```
Comment (pebrc) [inline pkg/controller/stackconfigpolicy/controller.go]:
```suggestion
		// Get the file settings secret. Create it if it doesn't exist.
        // This resolves the race condition from https://github.com/elastic/cloud-on-k8s/issues/8912
```

More concise. The part about the previous implementation seems irrelevant. Less cognitive overhead for readers.

File: pkg/controller/stackconfigpolicy/stackconfigpolicy.go (hunk 2 above)
Comment (pkoutsovasilis) [reply pkg/controller/stackconfigpolicy/stackconfigpolicy.go]: maybe we should let the caller decide to just log the error and continue?

File: pkg/controller/stackconfigpolicy/stackconfigpolicy.go (hunk 1 above)
Comment (pkoutsovasilis) [reply pkg/controller/stackconfigpolicy/stackconfigpolicy.go:23]: changed in 4858b4ad68975f696c294ab16283c93684c5061a

File: pkg/controller/stackconfigpolicy/stackconfigpolicy.go (hunk 2 above)
Comment (pkoutsovasilis) [reply pkg/controller/stackconfigpolicy/stackconfigpolicy.go]: went with my comment in 89592c7820f81768f43a63e0eaeac07119183286

File: pkg/controller/elasticsearch/driver/driver.go (hunk 3 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver.go]: changed in 8b9592b83e17abdc81e4c7f97dec6219137630f0

File: pkg/controller/stackconfigpolicy/controller.go (hunk 4 above)
Comment (pkoutsovasilis) [reply pkg/controller/stackconfigpolicy/controller.go]: changed in 344260ef3a5dc6cadc05685de2bab00ac6ec60d7

File: pkg/controller/elasticsearch/driver/driver.go [hunk 5]
```diff
@@ -417,6 +420,52 @@ func (d *defaultDriver) Reconcile(ctx context.Context) *reconciler.Results {
...
+	// Check each policy to see if it targets this ES cluster
+	for _, policy := range policyList.Items {
+		// Check if this policy's namespace and label selector match this ES cluster
+		matches, err := stackconfigpolicy.DoesPolicyMatchObject(&policy, es, operatorNamespace)
+		if err != nil {
+			log.Error(err, "Failed to check if StackConfigPolicy matches object", "scp_name", policy.Name, "scp_namespace", policy.Namespace, "es_name", es.Name, "es_namespace", es.Namespace)
+			continue
+		} else if !matches {
+			continue
+		}
```
Comment (barkbay) [inline pkg/controller/elasticsearch/driver/driver.go:471]:
```suggestion
		}
		var currentSecret corev1.Secret
		if err := c.Get(ctx, types.NamespacedName{Namespace: es.Namespace, Name: esv1.FileSettingsSecretName(es.Name)}, &currentSecret); err == nil {
			// Secret does exist
			return false, nil
		} else if !k8serrors.IsNotFound(err) {
			return false, err
		}
```

Otherwise I'm not sure I understand when we clean up the status and we stop requeing.

```yaml
    - lastTransitionTime: "2025-11-27T10:36:26Z"
      message: File settings secret is not reconciled
      status: "False"
      type: ReconciliationComplete
```

File: pkg/controller/elasticsearch/driver/driver.go [hunk 6]
```diff
@@ -417,6 +420,52 @@ func (d *defaultDriver) Reconcile(ctx context.Context) *reconciler.Results {
...
+	if err := c.List(ctx, &policyList); err != nil {
+		return false, err
+	}
+
+	// Check each policy to see if it targets this ES cluster
+	for _, policy := range policyList.Items {
+		// Check if this policy's namespace and label selector match this ES cluster
+		matches, err := stackconfigpolicy.DoesPolicyMatchObject(&policy, es, operatorNamespace)
+		if err != nil {
+			log.Error(err, "Failed to check if StackConfigPolicy matches object", "scp_name", policy.Name, "scp_namespace", policy.Namespace, "es_name", es.Name, "es_namespace", es.Namespace)
```
Comment (barkbay) [inline pkg/controller/elasticsearch/driver/driver.go]: Should we stop here and return that error? If not let's add comment to explain why.

File: pkg/controller/elasticsearch/driver/driver.go [hunk 7]
```diff
@@ -351,11 +353,12 @@ func (d *defaultDriver) Reconcile(ctx context.Context) *reconciler.Results {
...
 	}
 
-	// reconcile an empty File based settings Secret if it doesn't exist
 	if d.Version.GTE(filesettings.FileBasedSettingsMinPreVersion) {
-		err = filesettings.ReconcileEmptyFileSettingsSecret(ctx, d.Client, d.ES, true)
+		requeue, err := maybeReconcileEmptyFileSettingsSecret(ctx, d.Client, d.LicenseChecker, &d.ES, d.OperatorParameters.OperatorNamespace)
 		if err != nil {
 			return results.WithError(err)
+		} else if requeue {
+			results.WithReconciliationState(defaultRequeue.WithReason("File settings secret is not reconciled"))
```
Comment (barkbay) [inline pkg/controller/elasticsearch/driver/driver.go]:
```suggestion
			results.WithReconciliationState(
				defaultRequeue.WithReason(
					fmt.Sprintf("This cluster is targeted by at least one StackConfigPolicy, expecting Secret %s to be created by StackConfigPolicy controller", esv1.FileSettingsSecretName(d.ES.Name))),
			)
```

File: pkg/controller/elasticsearch/driver/driver.go (hunk 6 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver.go]: Added a comment to explain why it is this way in 765930880b90068ee66107add0c9bd0f8d41aa1c (this was driven by [this review comment](https://github.com/elastic/cloud-on-k8s/pull/8928#discussion_r2565342200))

File: pkg/controller/elasticsearch/driver/driver.go (hunk 5 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver.go:471]: good catch! the secret existence check should be in-place and I added it in 9e44f879b08337b3cd4417990dd9f9065e3a18d8

File: pkg/controller/elasticsearch/driver/driver.go (hunk 7 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver.go]: changed in 6fd2b1135c88d031eb9e8181ee474eec04b7cee1

File: pkg/controller/elasticsearch/driver/driver_test.go [hunk 8]
```diff
@@ -185,3 +192,275 @@ func (f *fakeSecurityClient) withFileTokens(namespacedService, tokenName string,
...
+					Spec: policyv1alpha1.StackConfigPolicySpec{
+						ResourceSelector: metav1.LabelSelector{
+							MatchLabels: map[string]string{
+								"team": "platform",
+							},
+						},
+					},
+				},
+			},
+			operatorNamespace: "elastic-system",
```
Comment (pebrc) [inline pkg/controller/elasticsearch/driver/driver_test.go]: This seems constant (same value in all tests)?

File: pkg/controller/elasticsearch/driver/driver.go [hunk 9]
```diff
@@ -417,6 +425,63 @@ func (d *defaultDriver) Reconcile(ctx context.Context) *reconciler.Results {
...
+	}
+
+	// Check each policy to see if it targets this ES cluster
+	for _, policy := range policyList.Items {
+		// Check if this policy's namespace and label selector match this ES cluster
+		matches, err := stackconfigpolicy.DoesPolicyMatchObject(&policy, es, operatorNamespace)
+		if err != nil {
+			// Do not return an err here as this potentially can block ES reconciliation if any SCP in the cluster
+			// has an invalid label selector, even if it doesn't target the current elasticsearch cluster.
+			log.Error(err, "Failed to check if StackConfigPolicy matches object", "scp_name", policy.Name, "scp_namespace", policy.Namespace, "es_name", es.Name, "es_namespace", es.Namespace)
```
Comment (barkbay) [inline pkg/controller/elasticsearch/driver/driver.go]:
```
Error: Duplicate key 'es_name'
```

And we don't need `es_namespace` I think


```suggestion
			log.Error(err, "Failed to check if StackConfigPolicy matches object", "scp_name", policy.Name, "scp_namespace", policy.Namespace)
```

⬇️ 

```json
{
    "service.version": "0.0.0-SNAPSHOT+00000000",
    "iteration": "1",
    "namespace": "default",
    "es_name": "elasticsearch-sample",
    "scp_name": "kibana-only-policy",
    "scp_namespace": "elastic-system",
    "error": "foo",
    "errorVerbose": "foo\ngithub.com/elastic/cloud-on-k8s/v3/pkg/controller/stackconfigpolicy.DoesPolicyMatchObject\n\t/Users/michael/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/stackconfigpolicy/stackconfigpolicy.go:21\ngithub.com/elastic/cloud-on-k8s/v3/pkg/controller/elasticsearch/driver.maybeReconcileEmptyFileSettingsSecret\n\t/Users/michael/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:454\ngithub.com/elastic/cloud-on-k8s/v3/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/Users/michael/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:357\ngithub.com/elastic/cloud-on-k8s/v3/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/Users/michael/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:305\ngithub.com/elastic/cloud-on-k8s/v3/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/Users/michael/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:193\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/Users/michael/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/Users/michael/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:461\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/Users/michael/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:421\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1\n\t/Users/michael/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:296\nruntime.goexit\n\t/Users/michael/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.darwin-arm64/src/runtime/asm_arm64.s:1268"
}
```

File: pkg/controller/elasticsearch/driver/driver_test.go [hunk 10]
```diff
@@ -185,3 +192,275 @@ func (f *fakeSecurityClient) withFileTokens(namespacedService, tokenName string,
...
+			existingSecrets:   []corev1.Secret{},
```
Comment (pebrc) [inline pkg/controller/elasticsearch/driver/driver_test.go]: Existing secrets is always empty.

File: pkg/controller/elasticsearch/driver/driver.go (hunk 9 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver.go]: fixed in acca844b2f7eae57561fd7af882f487a1391bda7

File: pkg/controller/elasticsearch/driver/driver_test.go (hunk 10 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver_test.go]: no longer, changed that in cf41336741f8648a665b8310f340b3274c874b6f

File: pkg/controller/elasticsearch/driver/driver_test.go (hunk 8 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver_test.go]: changed in c12bd6a8354413ca4954bcca5c3518ae27e1a342

File: pkg/controller/elasticsearch/driver/driver.go [hunk 11]
```diff
@@ -417,6 +425,63 @@ func (d *defaultDriver) Reconcile(ctx context.Context) *reconciler.Results {
...
+		if err != nil {
+			// Do not return an err here as this potentially can block ES reconciliation if any SCP in the cluster
+			// has an invalid label selector, even if it doesn't target the current elasticsearch cluster.
+			log.Error(err, "Failed to check if StackConfigPolicy matches object", "scp_name", policy.Name, "scp_namespace", policy.Namespace)
+			continue
+		} else if !matches {
+			continue
+		}
+
+		// Check if file-settings secret already exists
```
Comment (barkbay) [inline pkg/controller/elasticsearch/driver/driver.go]: I realised this morning that this is maybe the first thing we should do in this function, there is no reason to check this in the loop?

**Review by barkbay — APPROVED** [review]
LGTM

**Comment by barkbay** [comment]
buildkite test this -f p=gke,t=TestStackConfigPolicy*

File: pkg/controller/elasticsearch/driver/driver.go (hunk 11 above)
Comment (pkoutsovasilis) [reply pkg/controller/elasticsearch/driver/driver.go]: yep now that you caught that I did the same realisation, thx. changed in f93a901cc88b6bace4aec2fe66f7f84a121b1a1a

**Review by pebrc — APPROVED** [review]
LGTM!
