### PR TITLE
Set both beta and non-beta is-default-value annotation on storage class

### LINKED ISSUE #1766: 2 default StorageClasses were found
I just created a new 1.14 GKE cluster and I could not create an ES cluster because `2 default StorageClasses were found`:
```
1m  Warning  FailedCreate  statefulset/z-es-master                                  
  create Pod z-es-master-0 in StatefulSet z-es-master failed error: 
    Failed to create PVC elasticsearch-data-z-es-master-0: 
      persistentvolumeclaims "elasticsearch-data-bzz-es-master-0" is forbidden: 
        Internal error occurred: 2 default StorageClasses were found
```

We failed to change the default storage class because the existing storage class `standard` uses the `storageclass.kubernetes.io/is-default-class` annotation while we update the `storageclass.beta.kubernetes.io/is-default-class` annotation to false.

At the end, we have two storage classes with `storageclass.kubernetes.io/is-default-class: "true"`.

```shell
> k get sc standard -o yaml                                                                                                                                
allowVolumeExpansion: true                                                                                                                                                            
apiVersion: storage.k8s.io/v1                                                                                                                                                         
kind: StorageClass                                                                                                                                                                    
metadata:                                                                                                                                                                             
  annotations:                                                                                                                                                                        
    storageclass.beta.kubernetes.io/is-default-class: "false"                                                                                                                         
    storageclass.kubernetes.io/is-default-class: "true"
...
> k get sc standard-customized -o yaml                                                                                                                     
allowVolumeExpansion: true                       
apiVersion: storage.k8s.io/v1                                                                                                                                                         
kind: StorageClass                                                                        
metadata:                                                                                                                                                                             
  annotations:                                                                                                                                                                        
    kubectl.kubernetes.io/last-applied-configuration: {...}
    storageclass.kubernetes.io/is-default-class: "true"
...
```

In CI, the job `cloud-on-k8s-stack` fails for the same reason (https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-stack/32/console).

### PR DESCRIPTION
**Pull request by david-kow**
Fixes #1766, tested on K8s `1.12`, `1.13` and `1.14`.

### CODE REVIEW

File: hack/deployer/runner/gke.go [hunk 1]
```diff
@@ -269,9 +269,8 @@ EOF`, sc)).Run()
 		return err
 	}
 
-	cmd := fmt.Sprintf(
-		`kubectl patch storageclass %s -p '{ "metadata": { "annotations": { "storageclass.beta.kubernetes.io/is-default-class":"false"} } }'`,
-		defaultName)
+	patch := `'{ "metadata": { "annotations": { "storageclass.kubernetes.io/is-default-class":"false", "storageclass.beta.kubernetes.io/is-default-class":"false"} } }'`
```
Comment (sebgl) [inline hack/deployer/runner/gke.go]: A comment would be nice maybe?

Comment (david-kow) [reply hack/deployer/runner/gke.go]: It would :)
