### PR TITLE
[E2E] Fix "too many open files" error on Kind and file descriptor leaks

### LINKED ISSUE #9227: E2E job logs are not parsed correctly on Kind
```
{"log.level":"info","@timestamp":"2026-03-16T08:15:35.961Z","log.logger":"e2e-3vu1a","message":"Log stream ended","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","pod_name":"eck-e2e-3vu1a-bgn5b"}
--
{"log.level":"info","@timestamp":"2026-03-16T08:15:35.961Z","log.logger":"e2e-3vu1a","message":"Streaming pod logs","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","pod_name":"eck-e2e-3vu1a-bgn5b"}
{"log.level":"info","@timestamp":"2026-03-16T08:15:35.961Z","log.logger":"e2e-3vu1a","message":"Stream failure","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","pod":"eck-e2e-3vu1a-bgn5b","err":"failed to parse JSON log line \"failed to create fsnotify watcher: too many open files\": invalid character 'i' in literal false (expecting 'l')"}
```

### PR DESCRIPTION
**Pull request by barkbay**
## Summary

Fixes #9227

- Increase inotify `max_user_instances` from 128 to 512 for Kind/k3d CI environments. The default limit (128) is too low when running multiple containers with file watchers, causing "too many open files" errors from controller-runtime's fsnotify watchers at operator startup.
- Fix file descriptor leak in log stream retry loop where `defer stream.Close()` was inside a loop, causing streams to accumulate until function exit.
- Fix file descriptor leak in document indexing loop where `defer resp.Body.Close()` accumulated response bodies.

## Test plan

- [x] Verified fix on Kind CI - inotify limits were confirmed as root cause (original `max_user_instances` was 128)
- [x] E2E tests pass on Kind after the fix

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by prodsecmachine** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scan Engine |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/2392305f-c954-479f-bfb3-c2bda2076fa5?refs=5b2c30826190dde52feff614a5eae0d9b3b59fbc&source=prChecksComment) |
| :white_check_mark: | Licenses| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/2392305f-c954-479f-bfb3-c2bda2076fa5/license?refs=5b2c30826190dde52feff614a5eae0d9b3b59fbc&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Comment by barkbay** [comment]
Logs are back:

```
[...]
{"Time":"2026-03-16T09:54:50.56182695Z","Action":"run","Package":"github.com/elastic/cloud-on-k8s/v3/test/e2e","Test":"TestSmoke/Webhook_endpoint_should_not_be_empty"}
--
{"Time":"2026-03-16T09:54:50.561834903Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/v3/test/e2e","Test":"TestSmoke/Webhook_endpoint_should_not_be_empty","Output":"=== RUN   TestSmoke/Webhook_endpoint_should_not_be_empty\n"}
{"Time":"2026-03-16T09:54:50.565110611Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/v3/test/e2e","Test":"TestSmoke/Webhook_endpoint_should_not_be_empty","Output":"Retries (15m0s timeout): .\n"}
{"Time":"2026-03-16T09:54:50.565163935Z","Action":"run","Package":"github.com/elastic/cloud-on-k8s/v3/test/e2e","Test":"TestSmoke/Remove_Elasticsearch_if_it_already_exists"}
{"Time":"2026-03-16T09:54:50.565168765Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/v3/test/e2e","Test":"TestSmoke/Remove_Elasticsearch_if_it_already_exists","Output":"=== RUN   TestSmoke/Remove_Elasticsearch_if_it_already_exists\n"}
{"Time":"2026-03-16T09:54:50.628073398Z","Action":"output","Package":"github.com/elastic/cloud-on-k8s/v3/test/e2e","Test":"TestSmoke/Remove_Elasticsearch_if_it_already_exists","Output":"Retries (15m0s timeout): .\n"}
{"Time":"2026-03-16T09:54:50.628137913Z","Action":"run","Package":"github.com/elastic/cloud-on-k8s/v3/test/e2e","Test":"TestSmoke/K8S_should_be_accessible#01"}
[...]
```

File: .buildkite/scripts/test/set-deployer-config.sh [hunk 1]
```diff
@@ -23,6 +23,17 @@ set -eu
...
+# Increase inotify max_user_instances for Kind/k3d clusters to prevent "too many open files"
+# errors from controller-runtime's fsnotify watchers. The default (128) is too low when
+# running multiple containers with file watchers.
+if [[ "${E2E_PROVIDER:-}" == "kind" || "${E2E_PROVIDER:-}" == "k3d" ]]; then
+    if command -v sysctl &> /dev/null; then
+        sudo sysctl -w fs.inotify.max_user_instances=512 2>/dev/null || true
+    else
+        echo "Warning: sysctl not found, cannot increase inotify limits" >&2
+    fi
+fi
```
Comment (pkoutsovasilis) [inline .buildkite/scripts/test/set-deployer-config.sh:37]: Nit: IIUC this script is only invoked in CI. Developers running Kind locally via make switch-kind && make bootstrap-cloud won't benefit from this fix and may(?!) still hit the same "too many open files" error. Should we at least document the workaround in dev-setup.md?

Comment (barkbay) [reply .buildkite/scripts/test/set-deployer-config.sh:37]: It seems Docker Desktop configures its Linux VM with much higher inotify limits by default. My local Kind created with `make switch-kind ...` has `max_user_instances=8192` vs the CI's stock Ubuntu default of `128`. That's why I couldn't reproduce locally.

```
> docker exec eck-control-plane cat /proc/sys/fs/inotify/max_user_instances
8192
```

Linux developers running Kind on bare metal with stock distro defaults might still hit this, so yes I can add a note to the dev setup docs.

Comment (barkbay) [reply .buildkite/scripts/test/set-deployer-config.sh:37]: https://github.com/elastic/cloud-on-k8s/pull/9228/changes/5b2c30826190dde52feff614a5eae0d9b3b59fbc
