### PR TITLE
[E2E][GKE] Use labels to garbage collect unused Persistent Disks

### LINKED ISSUE #5935: [E2E][GKE][Deployer] Persistent Disks are not always cleaned up
I just noticed that the name of the GCE Persistent Disks created as the underlying storage infrastructure for GKE `PersistentVolumes` has changed. This name now only contains what seems to be a UUID, for example `pvc-355fb484-2993-4492-befc-f0bd84dddffa`. It prevents the deployer to remove them when a K8S cluster is deleted because of the name filter which is now wrong: https://github.com/elastic/cloud-on-k8s/blob/0d11cf4e016d1d542e74ad2690052ffd081fffb6/hack/deployer/runner/gke.go#L215-L220

One idea I'll explore is to set some labels on the Persistent Disks using the `labels` key of the CSI driver, see documentation [here](https://github.com/mattcary/gcp-compute-persistent-disk-csi-driver/blob/42b0d4b622fc386dbab244f6c7791943c39560ae/README.md#plugin-features).

Note that I already tried to use the `extra-labels` flag on the CSI nodes, but they crash with the following error: `Extra volume labels provided but not running controller`

### PR DESCRIPTION
**Pull request by barkbay**
This PR does 2 things:

1. It adds labels on resources created by a GKE cluster, including the GCE `Persistent Disks` provisioned as part of the K8S `PersistentVolumes` infrastructure.

* You can for example use these filters to list `Persistent Disks` by user:

```
gcloud compute disks list --filter='labels.username=michael_morello'
NAME                                         LOCATION        LOCATION_SCOPE  SIZE_GB  TYPE         STATUS
gke-barkbay-dev2-default-pool-83770c6e-qn81  europe-west2-a  zone            30       pd-ssd       READY
pvc-ba1162c2-aab9-496b-9838-06fb4a57945f     europe-west2-a  zone            2        pd-ssd       READY
gke-barkbay-dev2-default-pool-4d611566-qs39  europe-west2-b  zone            30       pd-ssd       READY
pvc-695d6dd8-a90b-4e85-960b-6db02de4277c     europe-west2-b  zone            2        pd-ssd       READY
gke-barkbay-dev2-default-pool-920a7074-5z24  europe-west2-c  zone            30       pd-ssd       READY
pvc-f2fd2f38-4712-406b-b0f3-bec8d0e88aa0     europe-west2-c  zone            2        pd-ssd       READY
gke-barkbay-dev1-default-pool-c28a62de-fk63  europe-west9-b  zone            30       pd-ssd       READY
pvc-8d3cb9ba-3639-4108-bfb4-744156b3be86     europe-west9-b  zone            1        pd-balanced  READY
gke-barkbay-dev1-default-pool-e7b51f8d-8wcw  europe-west9-a  zone            30       pd-ssd       READY
pvc-5e88cb38-05ea-4f3a-8a70-aba58bb695eb     europe-west9-a  zone            1        pd-balanced  READY
gke-barkbay-dev1-default-pool-66696f3e-ncvt  europe-west9-c  zone            30       pd-ssd       READY
pvc-b03174c7-7f4b-4c4d-a6f5-8534f6e9f737     europe-west9-c  zone            1        pd-balanced  READY
```

* Or filter by user and region:

```
gcloud compute disks list --filter='labels.username=michael_morello AND labels.region=europe-west2'
NAME                                         LOCATION        LOCATION_SCOPE  SIZE_GB  TYPE    STATUS
gke-barkbay-dev2-default-pool-83770c6e-qn81  europe-west2-a  zone            30       pd-ssd  READY
pvc-ba1162c2-aab9-496b-9838-06fb4a57945f     europe-west2-a  zone            2        pd-ssd  READY
gke-barkbay-dev2-default-pool-4d611566-qs39  europe-west2-b  zone            30       pd-ssd  READY
pvc-695d6dd8-a90b-4e85-960b-6db02de4277c     europe-west2-b  zone            2        pd-ssd  READY
gke-barkbay-dev2-default-pool-920a7074-5z24  europe-west2-c  zone            30       pd-ssd  READY
pvc-f2fd2f38-4712-406b-b0f3-bec8d0e88aa0     europe-west2-c  zone            2        pd-ssd  READY
```

* Or list unused disks:

```
gcloud compute disks list --filter='labels.username=michael_morello AND labels.region=europe-west9 AND -users:*'
NAME                                      LOCATION        LOCATION_SCOPE  SIZE_GB  TYPE         STATUS
pvc-8d3cb9ba-3639-4108-bfb4-744156b3be86  europe-west9-b  zone            1        pd-balanced  READY
pvc-5e88cb38-05ea-4f3a-8a70-aba58bb695eb  europe-west9-a  zone            1        pd-balanced  READY
pvc-b03174c7-7f4b-4c4d-a6f5-8534f6e9f737  europe-west9-c  zone            1        pd-balanced  READY
```

2. It attempts to detect and delete unsused disk using those labels.

Fix #5935

### CODE REVIEW

File: hack/deployer/runner/gke.go [hunk 1]
```diff
@@ -143,6 +158,63 @@ func (d *GKEDriver) Execute() error {
...
+	storageClasses := storagev1.StorageClassList{}
+	if err := yaml.Unmarshal([]byte(storageClassesYaml), &storageClasses); err != nil {
+		return err
+	}
+	labels, err := d.resourcesLabels()
+	if err != nil {
+		return err
+	}
+	for _, storageClass := range storageClasses.Items {
+		if storageClass.Provisioner != GoogleComputeEngineStorageProvider {
```
Comment (thbkrkr) [inline hack/deployer/runner/gke.go:181]: Why exclude PV created by the `kubernetes.io/gce-pd` provisioner?

File: hack/deployer/runner/gke.go [hunk 2]
```diff
@@ -173,24 +245,46 @@ func (d *GKEDriver) create() error {
...
+	labels, err := d.resourcesLabels()
+	if err != nil {
+		return err
+	}
 	return exec.NewCommand(`gcloud beta container --quiet --project {{.GCloudProject}} clusters create {{.ClusterName}} ` +
-		`--region {{.Region}} --no-enable-basic-auth --cluster-version {{.KubernetesVersion}} ` +
+		`--labels "` + labels + `" --region {{.Region}} --no-enable-basic-auth --cluster-version {{.KubernetesVersion}} ` +
 		`--machine-type {{.MachineType}} --disk-type pd-ssd --disk-size 30 ` +
 		`--local-ssd-count {{.LocalSsdCount}} --scopes {{.GcpScopes}} --num-nodes {{.NodeCountPerZone}} ` +
-		`--enable-stackdriver-kubernetes --addons HorizontalPodAutoscaling,HttpLoadBalancing ` +
```
[the remark this answers is not in the document]
Comment (barkbay) [reply hack/deployer/runner/gke.go:180]: `--enable-stackdriver-kubernetes` is deprecated. I don't think however that removing this flag disable log collection or monitoring, see default logging and monitoring behaviour [here](https://cloud.google.com/stackdriver/docs/solutions/gke/installing#available-logs). I still have some metrics in my GKE dashboard, and my saved queries in the logs explorer are still working (yeah must confess I'm using it from time to time 😄 )

Otherwise, yes, I'm removing it because it's deprecated, it's not related to this PR.

File: hack/deployer/runner/gke.go [hunk 3]
```diff
@@ -173,24 +245,46 @@ func (d *GKEDriver) create() error {
 		opts = append(opts, "--create-subnetwork range={{.ClusterIPv4CIDR}}", "--cluster-ipv4-cidr={{.ClusterIPv4CIDR}}", "--services-ipv4-cidr={{.ServicesIPv4CIDR}}")
 	}
 
+	labels, err := d.resourcesLabels()
+	if err != nil {
+		return err
+	}
 	return exec.NewCommand(`gcloud beta container --quiet --project {{.GCloudProject}} clusters create {{.ClusterName}} ` +
-		`--region {{.Region}} --no-enable-basic-auth --cluster-version {{.KubernetesVersion}} ` +
+		`--labels "` + labels + `" --region {{.Region}} --no-enable-basic-auth --cluster-version {{.KubernetesVersion}} ` +
```
[the remark this answers is not in the document]
Comment (barkbay) [reply hack/deployer/runner/gke.go:253]: This was mostly to have a consistent filtering expression when I was doing my tests:
* `gcloud compute disks list --filter='labels.cluster_name=barkbay-dev1'`

works the same as

* `gcloud compute instances list --filter='labels.cluster_name=barkbay-dev1`

File: hack/deployer/runner/gke.go (hunk 1 above)
Comment (barkbay) [reply hack/deployer/runner/gke.go:181]: > Why exclude PV created by the kubernetes.io/gce-pd provisioner?

Because it is the "in-tree provisioner" and it is supposed to be removed: https://kubernetes.io/blog/2021/12/10/storage-in-tree-to-csi-migration-status-update/#quick-recap-what-is-csi-migration-and-why-migrate
I think I can update the code to include it though.

Comment (thbkrkr) [reply hack/deployer/runner/gke.go:181]: Alright, TIL. So I'm for leaving it that way.

**Review by thbkrkr — APPROVED** [review]
LGTM
