### PR TITLE
Fix handling of HTTP CA

### LINKED ISSUE #1614: Improve handling public CA for ES certificate in Kibana
There are three cases to consider when it comes to ES TLS CA:
1. internal (operators own) CA,
1. external, non-public CA,
1. external, public CA.

Right now we don't handle 3. well (#1583) - since we always overwrite Kibanas CA it loses all public CAs. Right now we would require to provide ca.crt in ES TLS secret with public CA chain, which is not a good user experience.

We should stop overriding CAs when there is no ca.crt specified. This will handle case 3.
Case 2. will work as is, because users are expected to provide ca.crt for their internal CA (#1494).
To not regress in case 1. we would need to add ca.crt with operators CA to ES TLS cert secret.

### PR DESCRIPTION
**Pull request by charith-elastic**
More details can be found in #1614.
Briefly, this PR does the following:
- Treat the presence of `ca.crt` key in the secret as a signal to override the appropriate `*.certificate_authorities` setting of the associated stack application. 
- Add support for PKCS#8 encoded private keys.
- Update the documentation to clarify how custom certificates can be used.
- Update/add unit tests

Fixes #1614

### CODE REVIEW

File: pkg/controller/common/certificates/pem.go [hunk 1]
```diff
@@ -60,10 +61,29 @@ func EncodePEMPrivateKey(privateKey rsa.PrivateKey) []byte {
...
+		return nil, errors.Wrap(err, "failed to parse private key")
 	}
-	return x509.ParsePKCS1PrivateKey(block.Bytes)
+
+	rsaKey, ok := key.(*rsa.PrivateKey)
+	if !ok {
+		return nil, fmt.Errorf("expected an RSA private key but got %t", key)
+	}
+
+	return rsaKey, nil
```
Comment (pebrc) [inline pkg/controller/common/certificates/pem.go]: Am I mistaken or are we missing unit tests for this? Maybe an opportunity to add one (or two)?

Comment (charith-elastic) [reply pkg/controller/common/certificates/pem.go]: The reason I didn't add any unit tests is because these functions are just thin wrappers over standard library functions. Happy to add tests if you think differently.

Comment (pebrc) [reply pkg/controller/common/certificates/pem.go]: OK
