### PR TITLE
Fix incorrect modelled node shutdown API in Elasticsearch client

### LINKED ISSUE #5307: Node lifecycle API is incorrectly modelled
Node lifecycle APIs where added in 7.15.2 The integration was build against pre-release versions of Elasticsearch. It seems some attributes have changed since/or were incorrectly modelled to begin with: 

Node shutdown status: `STARTED` is not a valid value, `IN_PROGRESS` is missing 
Shard migration detail status: the field is called `shard_migrations_remaining` not `shard_migrations`

credits go to @barkbay for finding those bugs

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #5307 

Excluded from release notes because node shutdown functionality has not yet been shipped in any release.

### CODE REVIEW

File: pkg/controller/elasticsearch/client/model_test.go [hunk 1]
```diff
@@ -161,3 +161,32 @@ func TestLicenseUpdateResponse_IsSuccess(t *testing.T) {
 		})
 	}
 }
+
+func TestShutdownResponse(t *testing.T) {
+	nodeShudownSample := `{"nodes":[{"node_id":"PQKHA4xCQd2xErO2fUK-hg","type":"REMOVE","reason":"2331481","shutdown_startedmillis":1643648932189,"status":"IN_PROGRESS","shard_migration":{"status":"IN_PROGRESS","shard_migrations_remaining":1},"persistent_tasks":{"status":"COMPLETE"},"plugins":{"status":"COMPLETE"}}]}`
```
Comment (barkbay) [inline pkg/controller/elasticsearch/client/model_test.go:166]: nit: to make it easier to read
```suggestion
	nodeShudownSample := `{
	"nodes": [{
		"node_id": "PQKHA4xCQd2xErO2fUK-hg",
		"type": "REMOVE",
		"reason": "2331481",
		"shutdown_startedmillis": 1643648932189,
		"status": "IN_PROGRESS",
		"shard_migration": {
			"status": "IN_PROGRESS",
			"shard_migrations_remaining": 1
		},
		"persistent_tasks": {
			"status": "COMPLETE"
		},
		"plugins": {
			"status": "COMPLETE"
		}
	}]
}`
```

**Review by barkbay — APPROVED** [review]
LGTM
