### PR TITLE
fix: validate a user-supplied CA for the transport layer of Elasticsearch

### LINKED ISSUE #8952: ECK operator is indefinitely attempting to renew a user provided certificate
We've observed the behaviour below:

- A user has configured a custom CA for the transport layer of Elasticsearch.
```yaml
    service:
      metadata: {}
      spec:
        loadBalancerIP: 1.2.3.4
        type: LoadBalancer
    tls:
      certificate:
        secretName: magic-secret
      certificateAuthorities: {}
```
- The certificate has expired
- ECK is checking the cert validity and trying to renew it (in vain).

```json
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.238Z","log.logger":"es-monitoring","message":"Starting reconciliation run","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"149","namespace":"ns-elastic-XYZ-test","es-mon_name":"ABC-test-fe-04"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.238Z","log.logger":"es-monitoring","message":"Ending reconciliation run","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"149","namespace":"ns-elastic-XYZ-test","es-mon_name":"ABC-test-fe-04","took":0.000477282}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.238Z","log.logger":"remotecluster-controller","message":"Starting reconciliation run","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"149","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.253Z","log.logger":"remotecluster-controller","message":"Ending reconciliation run","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"149","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","took":0.015027524}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.407Z","log.logger":"elasticsearch-controller","message":"Ensuring no voting exclusions are set","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"156","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.431Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"156","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","took":0.228330921}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.432Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"157","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.444Z","log.logger":"elasticsearch-controller","message":"Certificate was not valid, should issue new: x509: certificate has expired or is not yet valid: current time 2025-12-03T13:28:49Z is after 2025-11-20T19:48:16Z","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"157","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","namespace":"ns-elastic-XYZ-test","subject":"CN=ABC-test-fe-04-es-default-1.node.ABC-test-fe-04.ns-elastic-XYZ-test.es.local,OU=X-test-fe-04","issuer":"CN=ABC","current_ca_subject":"CN=ABC","pod":"ABC-test-fe-04-es-default-1"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.444Z","log.logger":"elasticsearch-controller","message":"Issuing new certificate","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"157","namespace":"ns-elastic-XYZ-test","es_name":"XYZ-test-fe-04","pod_name":"XYZ-test-fe-04-es-default-1"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.448Z","log.logger":"elasticsearch-controller","message":"Certificate was not valid, should issue new: x509: certificate has expired or is not yet valid: current time 2025-12-03T13:28:49Z is after 2025-11-20T19:48:16Z","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"157","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","namespace":"ns-elastic-XYZ-test","subject":"CN=ABC-test-fe-04-es-default-0.node.ABC-test-fe-04.ns-elastic-XYZ-test.es.local,OU=ABC-test-fe-04","issuer":"CN=ABC","current_ca_subject":"CN=ABC","pod":"XYZ-test-fe-04-es-default-0"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.448Z","log.logger":"elasticsearch-controller","message":"Issuing new certificate","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"157","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","pod_name":"ABC-test-fe-04-es-default-0"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.451Z","log.logger":"elasticsearch-controller","message":"Certificate was not valid, should issue new: x509: certificate has expired or is not yet valid: current time 2025-12-03T13:28:49Z is after 2025-11-20T19:48:16Z","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"157","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","namespace":"ns-elastic-XYZ-test","subject":"CN=ABC-test-fe-04-es-default-2.node.ABC-test-fe-04.ns-elastic-XYZ-test.es.local,OU=ABC-test-fe-04","issuer":"CN=ABC","current_ca_subject":"CN=ABC","pod":"ABC-test-fe-04-es-default-2"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.451Z","log.logger":"elasticsearch-controller","message":"Issuing new certificate","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"157","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04","pod_name":"ABC-test-fe-04-es-default-2"}
{"log.level":"info","@timestamp":"2025-12-03T13:28:49.464Z","log.logger":"remotecluster-controller","message":"Starting reconciliation run","service.version":"3.0.0+89a41511","service.type":"eck","ecs.version":"1.4.0","iteration":"150","namespace":"ns-elastic-XYZ-test","es_name":"ABC-test-fe-04"}
```

**Potential enhancement**: ECK should validate custom CA expiration and emit clear error/event when CA is expired, instead of silently attempting to sign certificates with an invalid CA.

More information: https://github.com/elastic/sdh-control-plane/issues/11536

### PR DESCRIPTION
**Pull request by pkoutsovasilis**
## What does this PR do?

This pull request ensures that when a user supplies a custom CA for the Elasticsearch transport layer, the operator validates the CA’s expiration and prevents the system from endlessly attempting to renew certificates with an expired CA. Instead, it emits a clear error or event when an expired CA is detected.

## Why is it important?

Currently, if a user-supplied CA has expired, the ECK operator continually attempts (and fails) to renew certificates, resulting in silent failures and unclear operator behavior. This validation allows users to receive explicit feedback and error events when their CA is no longer valid, improving transparency and usability.

## Implementation details

- Adds validation logic for user-supplied CA certificates for the transport layer.
- The operator checks that the supplied CA is present, well-formed, and suitable for use with Elasticsearch transport layer encryption.
- If validation fails, the operator will report relevant errors in status, preventing misconfigured CAs from being used for cluster transport security.
- Unit tests have been added or updated to cover cases for valid and invalid CA submission.

## Related issues

- Closes: [#8952](https://github.com/elastic/cloud-on-k8s/issues/8952)

### CODE REVIEW

**Comment by prodsecmachine** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/2f178ef1-8777-4a0d-be5c-5e30fcd95e6c?refs=0da08e8ec56689277e481f060775b95f102f6f4c&source=prChecksComment) |
| :white_check_mark: | Licenses| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/2f178ef1-8777-4a0d-be5c-5e30fcd95e6c/license?refs=0da08e8ec56689277e481f060775b95f102f6f4c&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Comment by pkoutsovasilis** [comment]
buildkite test this -f p=gke,E2E_TAGS=es,t=TestCustom*

File: pkg/controller/common/certificates/ca_secret.go [hunk 1]
```diff
@@ -32,6 +36,24 @@ func ParseCustomCASecret(s corev1.Secret) (*CA, error) {
...
+func ValidateCustomCA(ctx context.Context, ca *CA) error {
+	now := time.Now()
+	log := ulog.FromContext(ctx)
+	switch {
+	case now.Before(ca.Cert.NotBefore):
+		return fmt.Errorf("the CA certificate is not yet valid")
+	case now.After(ca.Cert.NotAfter):
+		return fmt.Errorf("the CA certificate has expired")
+	case !PrivateMatchesPublicKey(ctx, ca.Cert.PublicKey, ca.PrivateKey):
+		return fmt.Errorf("the private key does not match the public one ")
```
Comment (pebrc) [inline pkg/controller/common/certificates/ca_secret.go]:
```suggestion
		return fmt.Errorf("the private key does not match the public one")
```

File: pkg/controller/common/certificates/ca_secret.go [hunk 2]
```diff
@@ -32,6 +36,24 @@ func ParseCustomCASecret(s corev1.Secret) (*CA, error) {
...
+	case now.After(ca.Cert.NotAfter.Add(-DefaultRotateBefore)):
+		log.Info("CA cert expired or soon to expire", "subject", ca.Cert.Subject, "expiration", ca.Cert.NotAfter)
```
Comment (pebrc) [inline pkg/controller/common/certificates/ca_secret.go]: Message could be clearer: we already know that the cert is not expired because otherwise we would have used the case in L47.
```suggestion
		log.Info("CA cert will expire soon", "subject", ca.Cert.Subject, "expiration", ca.Cert.NotAfter)
```

**Review by pebrc — APPROVED** [review]
LGTM. But it creates a behavioural gap between the transport and HTTP layer. We do not have a similar check for custom HTTP certificates. Example:  

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 9.2.0
  http:
    tls:
      certificate:
        secretName: custom-cert
```
Could you create a follow-up issue (and/or PR)?

File: pkg/controller/common/certificates/ca_secret.go (hunk 1 above)
Comment (pkoutsovasilis) [reply pkg/controller/common/certificates/ca_secret.go]: changed in ed8c9fd0e732a7295eea2a5facb8c9d65f315ab4

File: pkg/controller/common/certificates/ca_secret.go (hunk 2 above)
Comment (pkoutsovasilis) [reply pkg/controller/common/certificates/ca_secret.go]: changed in ed8c9fd0e732a7295eea2a5facb8c9d65f315ab4

**Comment by pkoutsovasilis** [comment]
Nice catch @pebrc ! I've created a follow-up issue here: https://github.com/elastic/cloud-on-k8s/issues/8990 

I'll work on a PR to add the same validation for the HTTP layer to ensure we have consistent behavior across both layers.

Quick question: since the `3.3.0` release is upon us, should I go ahead and merge this PR now, or should I wait?

**Comment by pebrc** [comment]
> Quick question: since the `3.3.0` release is upon us, should I go ahead and merge this PR now, or should I wait?

3.3. has been branched off so you can merge this anytime now but it won't be included in the release. We can discuss whether we consider this bug significant enough to warrant a back port to the release branch. I am not sure it is.

**Comment by pkoutsovasilis** [comment]
> 3.3. has been branched off so you can merge this anytime now but it won't be included in the release. We can discuss whether we consider this bug significant enough to warrant a back port to the release branch. I am not sure it is.

I totally agree with your assessment, I would even debate if this is a bug to begin with 🙂 Let's discuss this with the team
