### PR TITLE
Use Helm to deploy the E2E monitoring operator

### LINKED ISSUE #4247: [E2E] Kind test pipeline is broken
All Kind e2e jobs were not able run, see [Jenkins here](https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-kind-k8s-versions/detail/cloud-on-k8s-e2e-tests-kind-k8s-versions/353/pipeline).

The following error message is returned when the manifest for the monitoring resources is applied:

```
[2021-02-16T00:45:44.034Z] {"log.level":"info","@timestamp":"2021-02-16T00:45:43.861Z","log.logger":"e2e-ueq6e","message":"Deploying monitoring","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0"}

[2021-02-16T00:46:05.961Z] {"log.level":"info","@timestamp":"2021-02-16T00:46:04.759Z","log.logger":"e2e-ueq6e","message":"Command returned error code","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","command":"kubectl apply -f /tmp/eck-e2e/e2e-ueq6e/config_e2e_monitoring.yaml","message":"exit status 1"}

[2021-02-16T00:46:05.961Z] serviceaccount/metricbeat created

[....]

[2021-02-16T00:46:05.961Z] statefulset.apps/monitoring created

[2021-02-16T00:46:05.961Z] unable to recognize "/tmp/eck-e2e/e2e-ueq6e/config_e2e_monitoring.yaml": no matches for kind "Beat" in version "beat.k8s.elastic.co/v1beta1"

[2021-02-16T00:46:05.961Z] unable to recognize "/tmp/eck-e2e/e2e-ueq6e/config_e2e_monitoring.yaml": no matches for kind "Beat" in version "beat.k8s.elastic.co/v1beta1"

[2021-02-16T00:46:05.961Z] 

[2021-02-16T00:46:05.961Z] {"log.level":"info","@timestamp":"2021-02-16T00:46:04.759Z","log.logger":"e2e-ueq6e","message":"Deleting resources","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","file":"/tmp/eck-e2e/e2e-ueq6e/config_e2e_secrets.yaml"}

[2021-02-16T00:46:05.961Z] {"log.level":"info","@timestamp":"2021-02-16T00:46:05.766Z","log.logger":"e2e-ueq6e","message":"Deleting resources","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","file":"/tmp/eck-e2e/e2e-ueq6e/config_e2e_managed_namespaces.yaml"}

[2021-02-16T00:46:24.020Z] {"log.level":"info","@timestamp":"2021-02-16T00:46:22.729Z","log.logger":"e2e-ueq6e","message":"Deleting resources","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","file":"/tmp/eck-e2e/e2e-ueq6e/config_e2e_operator_namespaces.yaml"}

[2021-02-16T00:46:29.273Z] {"log.level":"info","@timestamp":"2021-02-16T00:46:28.262Z","log.logger":"e2e-ueq6e","message":"Deleting resources","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","file":"/tmp/eck-e2e/e2e-ueq6e/config_e2e_roles.yaml"}

[2021-02-16T00:46:29.836Z] {"log.level":"info","@timestamp":"2021-02-16T00:46:29.782Z","log.logger":"e2e-ueq6e","message":"Deleting resources","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","file":"/tmp/eck-e2e/e2e-ueq6e/config_e2e_rbac.yaml"}

[2021-02-16T00:46:51.742Z] {"log.level":"info","@timestamp":"2021-02-16T00:46:49.299Z","log.logger":"e2e-ueq6e","message":"Cleaning up the scratch directory","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","directory":"/tmp/eck-e2e/e2e-ueq6e"}

[2021-02-16T00:46:51.742Z] {"log.level":"error","@timestamp":"2021-02-16T00:46:49.300Z","log.logger":"e2e-ueq6e","message":"Failed to run e2e tests","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","error":"command failed: [kubectl apply -f /tmp/eck-e2e/e2e-ueq6e/config_e2e_monitoring.yaml]: exit status 1","errorVerbose":"exit status 1\ncommand failed: [kubectl apply -f /tmp/eck-e2e/e2e-ueq6e/config_e2e_monitoring.yaml]\ngithub.com/elastic/cloud-on-k8s/test/e2e/cmd/run.(*helper).exec\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/cmd/run/run.go:649 [...]

[2021-02-16T00:46:51.742Z] Error: command failed: [kubectl apply -f /tmp/eck-e2e/e2e-ueq6e/config_e2e_monitoring.yaml]: exit status 1
```

### PR DESCRIPTION
**Pull request by charith-elastic**
Monitoring depends on the CRDs being present (before the operator is deployed) and has its own operator to orchestrate the Beats. This PR replaces the monitoring operator deployment with Helm as well. 

Related to #4203

Fixes #4247

### CODE REVIEW

File: test/e2e/cmd/run/run.go [hunk 1]
```diff
@@ -297,29 +297,71 @@ func (h *helper) createRoles() error {
 	return h.kubectlApplyTemplateWithCleanup("config/e2e/roles.yaml", h.testContext)
 }
 
-func (h *helper) installOperator() error {
-	log.Info("Installing the operator")
-	values, err := h.renderTemplate("config/e2e/helm-values.yaml", h.testContext)
-	if err != nil {
-		return fmt.Errorf("failed to generate Helm values: %w", err)
+func (h *helper) installE2EOperator() error {
```
Comment (pebrc) [inline test/e2e/cmd/run/run.go:300]: Should this be called something like `operatorUnderTest` rather then e2e operator (also in other places). Just to make clear it is the test subject?

File: test/e2e/cmd/run/run.go [hunk 2]
```diff
@@ -297,29 +297,71 @@ func (h *helper) createRoles() error {
...
+	log.Info("Installing the E2E operator")
+
+	installCRDs := false
```
Comment (pebrc) [inline test/e2e/cmd/run/run.go:303]: This took me a while to wrap my head around. Initially I thought that we are always testing the 1.4.0 CRDs and not the ones of the version under test until I realised that we just setting the Docker image but the CRDs and other manifests are actually based on the version under test. I think maybe a comment somewhere would be good to make the casual reader aware of this.

**Review by pebrc — APPROVED** [review]
LGTM 🤞

File: test/e2e/cmd/run/run.go (hunk 2 above)
Comment (charith-elastic) [reply test/e2e/cmd/run/run.go:303]: Yes, it's not ideal but it's not much different from how it used to be either. Since CRDs are global, we have to install the current version in order to properly test the operator. That means not being able to use the all-in-one.yaml for 1.4.0 because it would overwrite the CRDs. We could use Helm proper, but that means having to install Helm into the CI image, syncing with the Elastic Helm repo etc. I didn't think the additional complexity was worth it given how complicated the whole thing is already.

**Review by pebrc — APPROVED** [review]
