### PR TITLE
Fix trial license validation issues

### LINKED ISSUE #2878: Flaky E2E test: TestEnterpriseTrialLicense
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-master/146/testReport/github/com_elastic_cloud-on-k8s_test_e2e_es/TestEnterpriseTrialLicense_Check_enterprise_trial_license_is_annotated_as_invalid/

```
=== RUN   TestEnterpriseTrialLicense/Check_enterprise_trial_license_is_annotated_as_invalid
Retries (5m0s timeout): ....................................................................................................
{"log.level":"error","@timestamp":"2020-04-14T13:36:43.016Z","message":"stopping early","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","error":"test failure","error.stack_trace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/elastic/cloud-on-k8s/test/e2e/test.StepList.RunSequential\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/step.go:43\ngithub.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/es/license_test.go:128\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:909"}
    --- FAIL: TestEnterpriseTrialLicense/Check_enterprise_trial_license_is_annotated_as_invalid (300.00s)
        utils.go:84: 
            	Error Trace:	utils.go:84
            	Error:      	Received unexpected error:
            	            	trial license should have validation annotation [false] and annotation was present [true]
            	Test:       	TestEnterpriseTrialLicense/Check_enterprise_trial_license_is_annotated_as_invalid
```

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #2878 

What this PR does:
* introduce concept of trial activation where we keep the trial key around until trial successfully activated
* fixes erroneous validation messages as seen in #2878 
* fixes a situation where an operator crash or a k8s API error would prevent users from ever successfully starting a trial (not yet observed in the wild but possible)

### CODE REVIEW

**Comment by pebrc** [comment]
@sebgl I made the changes we discussed out-of-band

File: pkg/controller/license/trial/trial_controller.go [hunk 1]
```diff
@@ -80,85 +78,95 @@ func (r *ReconcileTrials) Reconcile(request reconcile.Request) (reconcile.Result
...
+		if err := r.trialState.InitTrialLicense(&license); err != nil {
+			return reconcile.Result{}, err
 		}
-		status := verifier.Valid(license, time.Now())
+	case trialSecretPopulated:
+		status := r.trialState.LicenseVerifier().Valid(license, time.Now())
 		if status != licensing.LicenseStatusValid {
 			setValidationMsg(&secret, userFriendlyMsgs[status])
+		} else {
+			// valid trial license: complete trial activation
```
Comment (sebgl) [inline pkg/controller/license/trial/trial_controller.go:103]: I would add: `(no-op in most cases)`

File: pkg/controller/license/trial/trial_controller.go [hunk 2]
```diff
@@ -80,85 +78,95 @@ func (r *ReconcileTrials) Reconcile(request reconcile.Request) (reconcile.Result
...
 	trialSecretPopulated := license.IsMissingFields() == nil
-	if r.isTrialRunning() && trialSecretPopulated {
-		verifier := licensing.Verifier{
-			PublicKey: r.trialPubKey,
+	switch {
+	case r.trialState.IsTrialRunning() && !trialSecretPopulated:
+		// if the trial license fields are not populated at this point a user is trying to start a trial a second time
+		// with an empty trial secret, which is not a supported use case.
+		setValidationMsg(&secret, trialOnlyOnceMsg)
+	case !trialSecretPopulated && r.trialState.IsTrialActivationInProgress():
```
Comment (sebgl) [inline pkg/controller/license/trial/trial_controller.go:93]: Having a single `trialState.IsStarted()` instead of `trialState.IsTrialRunning()` and `trialState.IsTrialActivationInProgress()` would simplify the reading a little bit?

I think the switch would read better with more cases, consistent conditions ordering, and a return statement everywhere:

```go

switch {
    case !trialSecretPopulated && trialState.IsStarted():
        // user wants to start a trial a 2nd time
        return invalidOperation(secret, trialOnlyOnceMsg)
    case !trialSecretPopulated && !trialState.IsStarted():
        // user wants to init a trial for the first time
        return initTrial(secret)
     case trialSecretPopulated && !validLicense(license):
        // the existing license is invalid (expired or tampered)
        return invalidOperation(secret, invalidLicenseMsg(license))
    case trialSecretPopulated && validLicense(license) && !trialState.IsStarted():
        // valid license, let's consider the trial as started
        return trialState.SetStarted()
    case trialSecretPopulated && validLicense(license) && trialState.IsStarted():
        // all good, nothing to do
        return nil
}
```

File: pkg/controller/common/license/trial.go [hunk 3]
```diff
@@ -9,74 +9,148 @@ import (
...
+}
 
-	if err := populateTrialLicense(l); err != nil {
-		return nil, pkgerrors.Wrap(err, "failed to populate trial license")
+// NewTrialStateFromStatus reconstructs trial state from a trial status secret.
+func NewTrialStateFromStatus(trialStatus corev1.Secret) (TrialState, error) {
+	// create new keys if the operator failed just before the trial was started
+	trialActivation, err := strconv.ParseBool(string(trialStatus.Data[TrialActivationKey]))
+	if err == nil && trialActivation {
+		return NewTrialState()
```
Comment (sebgl) [inline pkg/controller/common/license/trial.go:56]: should we handle a case where the operator starts, sees activation is in progress, but some license secrets already exist out there?

File: pkg/controller/license/trial/trial_controller.go [hunk 4]
```diff
@@ -80,85 +78,95 @@ func (r *ReconcileTrials) Reconcile(request reconcile.Request) (reconcile.Result
...
+		return err
+	}
+	r.trialState = state
+	return nil
+}
 
+func (r *ReconcileTrials) completeTrialActivation() (reconcile.Result, error) {
+	if r.trialState.CompleteTrialActivation() {
+		// requeue to update trial status
+		return reconcile.Result{Requeue: true}, nil
```
Comment (sebgl) [inline pkg/controller/license/trial/trial_controller.go:167]: why don't we update the status at this reconciliation instead of requeuing?

Comment (pebrc) [reply pkg/controller/license/trial/trial_controller.go:167]: We can. The reason I did not do it initially was that I thought we might run into conflicts when we update twice in the same reconciliation. Also it felt easier to reason about the code when all status updates happen in `reconcileStatus`

File: pkg/controller/license/trial/trial_controller.go (hunk 2 above)
Comment (pebrc) [reply pkg/controller/license/trial/trial_controller.go]: Much better!

File: pkg/controller/common/license/trial.go (hunk 3 above)
Comment (pebrc) [reply pkg/controller/common/license/trial.go:56]: Thinking about this some more, I think we got that covered. I see two cases where this might happen:
1. Crash/Restart after generating the trial license:
   * we start trial activation, create status secret
   * we then initialise the license, update license
   * crash/restart of operator: status+license match up and we continue to complete trial activation
2. License exists from a previous installation or similar
   * we start trial activation, create status secret
   * existing license + status mismatch we annotate the license
   * operator crashes at any point after that
   * existing license+status still mismatch 
   * we could now delete the license/re-initialise it but my thinking is we should leave that to the user. What do you think?

**Comment by pebrc** [comment]
Jenkins test this please

File: pkg/controller/license/trial/trial_controller.go [hunk 5]
```diff
@@ -76,89 +74,120 @@ func (r *ReconcileTrials) Reconcile(request reconcile.Request) (reconcile.Result
...
-		r.trialPubKey = key
-		return nil
-	}
-	pubkeyBytes, err := x509.MarshalPKIXPublicKey(r.trialPubKey)
-	if err != nil {
-		return err
-	}
-	if bytes.Equal(trialStatus.Data[licensing.TrialPubkeyKey], pubkeyBytes) {
-		return nil
+		// requeue to update trial status
```
Comment (sebgl) [inline pkg/controller/license/trial/trial_controller.go:167]: is it requeueing?

Comment (pebrc) [reply pkg/controller/license/trial/trial_controller.go:167]: 😞 left over from previous version.

File: pkg/controller/common/license/trial.go (hunk 3 above)
Comment (sebgl) [reply pkg/controller/common/license/trial.go:56]: > Crash/Restart after generating the trial license:
we start trial activation, create status secret
we then initialise the license, update license
crash/restart of operator: status+license match up and we continue to complete trial activation

when that happens, aren't we regenerating a new pubkey, in which case status+license don't match up?

Comment (sebgl) [reply pkg/controller/common/license/trial.go:56]: Would it be better to check existing licenses in that situation?
* operator starts and sees the status reports activation in progress
    * check existing licenses:
        * if there are signed licenses already, use the existing status pubkey, and remove the trial activation flag from the status secret
        * if there are no signed licenses (but maybe unsigned ones), regenerate a private/public keypair

Comment (pebrc) [reply pkg/controller/common/license/trial.go:56]: You are right, there is another gap here.

File: pkg/controller/license/trial/trial_controller.go [hunk 6]
```diff
@@ -76,89 +75,132 @@ func (r *ReconcileTrials) Reconcile(request reconcile.Request) (reconcile.Result
...
+		return nil
+	}
+	trialStatus.Data = expected.Data
+	return r.Update(&trialStatus)
 }
 
-func (r *ReconcileTrials) isTrialRunning() bool {
-	return r.trialPubKey != nil
-}
+func recoverState(license licensing.EnterpriseLicense, trialStatus corev1.Secret, err error) (licensing.TrialState, error) {
```
Comment (sebgl) [inline pkg/controller/license/trial/trial_controller.go:153]: leftover `err` argument that should not be there?
