### PR TITLE
Use Elastic Stack version in upgrade tests

### LINKED ISSUE #2560: Decrease the number of stack versions tested in the E2E tests
Running all the E2E tests involve to pull multiple Docker images:
* 1 APM: ${stack_version}
* 3 KB images: 7.4.0, 7.4.2, ${stack_version}
* 7 ES: 6.8.5, 7.1.0, 7.3.0, 7.3.2, 7.4.0, 7.4.2, 7.6.0, (+ ${stack_version} which is often already in the list, exception for 7.1.1 and 7.2.1)

It should be fine, except [it takes up space](https://github.com/elastic/cloud-on-k8s/issues/1096#issuecomment-585662882) and correct me if I'm wrong, there is no real rational way that founds this list of versions.

The number of images is increased to test upgrade scenarios. I think we can improve this but we also need to take in account the fact that we test several stack versions with the [`cloud-on-k8s-stack`](https://devops-ci.elastic.co/job/cloud-on-k8s-stack/) job: 6.8.5, 7.1.1, 7.2.1, 7.3.2, 7.4.2, 7.6.0.

* Kibana upgrades (always include an ES cluster)
7.4.0->7.4.2 TestVersionUpgrade 3n +es in 7.4.2
7.4.0->7.4.2 TestVersionUpgradeAndRespec 3n +es in 7.4.2

* Elasticsearch upgrades
6.8.5->7.3.2 TestVersionUpgradeSingleNode68xTo73x 1n
6.8.5->7.3.2 TestVersionUpgradeTwoNodes68xTo73x   2n
6.8.5->7.3.0 TestVersionUpgrade3Nodes68xTo73x     1n
6.8.5->7.3.0 TestVersionUpgradeSingleMaster68xToNewNodeSet73x 1n
6.8.5->7.3.0 TestVersionUpgradeSingleMaster68xToMore73x 1n->2n
7.1.0->7.3.2 TestVersionUpgradeSingle710To730 1n
7.4.2->7.6.0 TestVersionUpgradeSingle740To760 1n

We could reduce this to 4 versions:
* `from68x` -> `to7xFrom68x`, for the `TestVersionUpgrade.*68x.*` tests (only for ES)
* `from7x` -> `to7x`, for all the other upgrades (Kibana and ES)

I may be interesting to find out which versions are mandatory to test and which can be replaced. In other words, which versions cause a particular behavior of the operator?

### PR DESCRIPTION
**Pull request by thbkrkr**
This commit decreases the number of version of the Elastic Stack that is
involved when executing all the E2E tests. It also allows testing more
different combinations of version upgrades.

* Define static versions for min 68x, min 7x and latest 7x
* Use the Elastic Stack version in the version upgrade tests:
  * **from** the min 68x version **to** the Elastic Stack version
  * **from** the Elastic Stack Version **to** the latest 7x version
* Skip some tests if they are not relevant to the Elastic Stack version
* Use the latest version 7.x as the default value for the Elastic Stack version

Resolves #2560.
Relates to #2253, #2565.

### CODE REVIEW

**Comment by thbkrkr** [comment]
Projection with the Elastic Stack versions `6.8.5`, `7.1.1`, `7.2.2`, `7.3.2`, `7.4.2`, `7.5.2`, `7.6.0`:
```go
6.8.5 | 68x->7x | skipped
6.8.5 |  7x->7x | skipped
7.1.1 | 68x->7x | 6.8.5->7.1.1
7.1.1 |  7x->7x | skipped
7.2.2 | 68x->7x | 6.8.5->7.2.2
7.2.2 |  7x->7x | 7.2.2->7.6.0
7.3.2 | 68x->7x | 6.8.5->7.3.2
7.3.2 |  7x->7x | 7.3.2->7.6.0
7.4.2 | 68x->7x | 6.8.5->7.4.2
7.4.2 |  7x->7x | 7.4.2->7.6.0
7.5.2 | 68x->7x | 6.8.5->7.5.2
7.5.2 |  7x->7x | 7.5.2->7.6.0
7.6.0 | 68x->7x | 6.8.5->7.6.0
7.6.0 |  7x->7x | skipped
```

**Comment by thbkrkr** [comment]
Projection with the Elastic Stack versions `6.8.5`, `7.1.1`, `7.2.2`, `7.3.2`, `7.4.2`, `7.5.2`, `7.6.0`:
```ocaml
6.8.5 | 68x->7x | skipped
6.8.5 |  7x->7x | skipped
7.1.1 | 68x->7x | 6.8.5->7.1.1
7.1.1 |  7x->7x | skipped
7.2.2 | 68x->7x | 6.8.5->7.2.2
7.2.2 |  7x->7x | 7.2.2->7.6.0
7.3.2 | 68x->7x | 6.8.5->7.3.2
7.3.2 |  7x->7x | 7.3.2->7.6.0
7.4.2 | 68x->7x | 6.8.5->7.4.2
7.4.2 |  7x->7x | 7.4.2->7.6.0
7.5.2 | 68x->7x | 6.8.5->7.5.2
7.5.2 |  7x->7x | 7.5.2->7.6.0
7.6.0 | 68x->7x | 6.8.5->7.6.0
7.6.0 |  7x->7x | skipped
```

File: test/e2e/kb/version_upgrade_test.go [hunk 1]
```diff
@@ -20,15 +20,21 @@ import (
 )
 
 func TestVersionUpgrade(t *testing.T) {
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: For consistency with ES, it would be nice to test:
* from min 6.x to current 7.x
* from current 7.x to latest 7.x

File: test/e2e/es/version_upgrade_test.go [hunk 2]
```diff
@@ -8,105 +8,123 @@ import (
...
 
 	RunESMutation(t, initial, mutated)
 }
 
-func TestVersionUpgradeSingle710To730(t *testing.T) {
-	initial := elasticsearch.NewBuilder("test-version-up-1-710-to-732").
-		WithVersion("7.1.0").
+func TestVersionUpgradeSingle7xTo7x(t *testing.T) {
+	test.SkipIfMinVersion68x(t)
+	test.SkipIfFrom7xTo7x(t)
```
[the remark this answers is not in the document]
Comment (sebgl) [reply test/e2e/es/version_upgrade_test.go]: Or maybe we should have a higher-level helper here:
```go
test.SkipUpgradeToLatest7x(t)
```

which translates to:

```go
if !is7x(currentVersion) || isLatest7x(currentVersion)
```

File: test/e2e/test/version.go [hunk 3]
```diff
@@ -6,19 +6,27 @@ package test
 
 import (
 	"testing"
+)
 
-	"github.com/stretchr/testify/require"
-	"k8s.io/apimachinery/pkg/util/version"
+// Elastic Stack versions used in the E2E tests
+var (
```
Comment (charith-elastic) [inline test/e2e/test/version.go]: I think these can be `const`

File: test/e2e/test/version.go [hunk 4]
```diff
@@ -6,19 +6,27 @@ package test
...
+	MinVersion7x = "7.1.1"
+	// Current latest version for 7.x
+	LatestVersion7x = "7.6.0" // version to synchronize with the latest release of the Elastic Stack
 )
 
-// MinVersionOrSkip run this test only if the server has at least version v.
-func MinVersionOrSkip(t *testing.T, v string) {
-	info, err := ServerVersion()
-	require.NoError(t, err)
+func SkipIfMinVersion68x(t *testing.T) {
```
Comment (charith-elastic) [inline test/e2e/test/version.go]: May be we can have a generic function instead?

```go
func SkipIfStackVersionIsBetween(t *testing.T, minVersion, maxVersion string) {
   // code to skip if the minVersion <= test Stack version <= maxVersion 
}
```

File: test/e2e/es/version_upgrade_test.go [hunk 5]
```diff
@@ -8,105 +8,123 @@ import (
...
 			PodTemplate: elasticsearch.ESPodTemplate(elasticsearch.DefaultResources),
 		})
 
 	RunESMutation(t, initial, mutated)
 }
 
-func TestVersionUpgradeSingleMaster68xToMore73x(t *testing.T) {
+func TestVersionUpgradeSingleMaster68xToMore7x(t *testing.T) {
+	test.SkipIfMinVersion68x(t)
+	test.SkipIfFrom7xTo7x(t)
```
[the remark this answers is not in the document]
Comment (thbkrkr) [reply test/e2e/es/version_upgrade_test.go]: No reason, I made a mistake.

File: test/e2e/test/version.go (hunk 4 above)
Comment (thbkrkr) [reply test/e2e/test/version.go]: Yes, let's try to do something more generic. However, I don't feel that using an interval of version will be the most easy way to express how to skip an invalid upgrade.

**Comment by thbkrkr** [comment]
https://github.com/elastic/cloud-on-k8s/pull/2570#discussion_r380054157 makes me think that we should avoid to duplicate the tests for Kibana to test from 68x.

So far I have done:
```go
68x->v       if v.major = 7
v->latest7x  if v != latest7x
```

Looking back, I see the following pattern that is more generic:
```go
// what we have today
latest6x -> v         if v.major == 7
       v -> latest7x  if v != latest7x (implicitly v.major == 6 || v.major == 7)

// in the future
latest7x -> v         if v.major == 8
       v -> latest8x  if v != latest8x && (v.major == 7 || v.major == 8)

latest8x -> v         if v.major == 9
       v -> latest9x  if v != latest9x && (v.major == 8 || v.major == 9)

...
```

This led me to have a generic `SkipInvalidUpgrade` function and to let each test decide whether the Elastic Stack version is used as source or as destination in the upgrade path.

New projection:
```go
6.8.5 | latest6x -> v | skipped
6.8.5 | v -> latest7x | 6.8.5->7.6.0
7.1.1 | latest6x -> v | 6.8.5->7.1.1
7.1.1 | v -> latest7x | 7.1.1->7.6.0
7.2.2 | latest6x -> v | 6.8.5->7.2.2
7.2.2 | v -> latest7x | 7.2.2->7.6.0
7.3.2 | latest6x -> v | 6.8.5->7.3.2
7.3.2 | v -> latest7x | 7.3.2->7.6.0
7.4.2 | latest6x -> v | 6.8.5->7.4.2
7.4.2 | v -> latest7x | 7.4.2->7.6.0
7.5.2 | latest6x -> v | 6.8.5->7.5.2
7.5.2 | v -> latest7x | 7.5.2->7.6.0
7.6.0 | latest6x -> v | 6.8.5->7.6.0
7.6.0 | v -> latest7x | skipped
```

File: test/e2e/test/version.go [hunk 6]
```diff
@@ -7,18 +7,39 @@ package test
...
+)
 
-	min := version.MustParseGeneric(v)
-	actual := version.MustParseGeneric(info.GitVersion)
-	if !actual.AtLeast(min) {
+// SkipInvalidUpgrade skips a test that would do an invalid upgrade.
+func SkipInvalidUpgrade(t *testing.T, srcVersion string, dstVersion string) {
+	isValid, err := isValidUpgrade(srcVersion, dstVersion)
+	if err != nil {
+		t.Fatal("Fail to parse Elastic Stack version", "err", err.Error())
```
Comment (charith-elastic) [inline test/e2e/test/version.go]: Nit: I think this would just concatenate everything together and come out as `Fail to parse Elastic Stack versionerrerror message...`.  Maybe `isValidUpgrade` should return a wrapped error to provide more information. I don't know whether that's overkill for a test function though.

```suggestion
		t.Fatalf("Failed to determine the validity of the upgrade path: %v", err)
		...
func isValidUpgrade(from string, to string) (bool, error) {
	srcVer, err := version.Parse(from)
	if err != nil {
		return false, fmt.Errorf("failed to parse version '%s': %w", from, err)
	}
	...
}
```

File: test/e2e/test/version.go [hunk 7]
```diff
@@ -33,11 +34,11 @@ func SkipInvalidUpgrade(t *testing.T, srcVersion string, dstVersion string) {
 func isValidUpgrade(from string, to string) (bool, error) {
 	srcVer, err := version.Parse(from)
 	if err != nil {
-		return false, err
+		return false, fmt.Errorf("failed to parse version '%s': %w", from, err)
 	}
 	dstVer, err := version.Parse(to)
 	if err != nil {
-		return false, err
+		return false, fmt.Errorf("failed to parse version '%s': %w", from, err)
```
Comment (charith-elastic) [inline test/e2e/test/version.go]: Should be `to` here :smile: 

```suggestion
		return false, fmt.Errorf("failed to parse version '%s': %w", to, err)
```

Comment (thbkrkr) [reply test/e2e/test/version.go]: copy/paste too fast :no_mouth:
