### PR TITLE
Ensure Agent configuration and state persist across restarts in Fleet mode

### LINKED ISSUE #8819: Agent configuration path should be writeable and persisted
Issue extracted from https://github.com/elastic/elastic-agent/issues/5185#issuecomment-3149821203

In managed mode, Agent receives configuration from Fleet, and this configuration needs to reside in the state path so that it persists across restarts.

The recommendations from the Agent team are the following:

* Keep `CONFIG_PATH` pointing to the state path.
* If a user wants to mount additional static config into the Pod, they can do that and they can point to it using the -c argument to elastic-agent container ... cmd, and this can safely live outside the state path.

As a side note not having the configuration directory writeable (because of some dropped capabilities, read only fs ...) can also lead to the following error at startup:

```
agent container initialisation - effective capabilities
agent container initialisation - ambient capabilities
agent container initialisation - chown paths
Warning: cannot chown agent paths without CAP_CHOWN or CAP_DAC_OVERRIDE capabilities
Policy selected for enrollment:  eck-fleet-server
Error: could not create new vault: failed to create vault path: /etc/agent/vault, err: mkdir /etc/agent/vault: permission denied
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.19/fleet-troubleshooting.html
Error: enrollment failed: exit status 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.19/fleet-troubleshooting.html
```

A workaround is then to apply the changes suggested above:

```yaml
        containers:
        - name: agent
          env:
            - name: STATE_PATH
              value: /usr/share/elastic-agent/state
            - name: CONFIG_PATH
              value: /usr/share/elastic-agent/state
          args:
            - -e
            - -c
            - /etc/agent/elastic-agent.yml
```

### PR DESCRIPTION
**Pull request by naemono**
Resolves #8819
Related: https://github.com/elastic/elastic-agent/issues/5185

## Testing procedure

Bring es/kibana/agents online. Verified fleet page in kibana in fleet-mode, verified logs of agents themselves in non-fleet-mode. Restarted/killed agent pods, and ensured that the ones in the fleet-ui in Kibana didn't change names, or additional new ones weren't added.

**For advanced configuration:**
Add the following to the Agent manifest:
```
  config:
    fleet:
      enabled: true
    providers.kubernetes:
      add_resource_metadata:
        deployment: true
```
Exec into running agent pod and execute `elastic-agent inspect` verify that the following is present in the output:
```
providers:
  kubernetes:
    add_resource_metadata:
      deployment: true
```

## Tested
- [x] 9.2.0-snapshot (fleet mode)
- [x] 9.2.0-snapshot (standalone mode)
- [x]  9.2.0-snapshot (fleet mode + advanced configuration)
- [x] 8.19 (fleet mode)
- [x] 8.19 (standalone mode)
- [ ] 8.19 (fleet mode + advanced configuration)
- [x] 8.13 (fleet mode)
- [x] 8.13 (standalone mode)
- [x] 8.13 (fleet mode + advanced configuration)
- [x] 7.17 (fleet mode)
- [x] 7.17 (standalone mode)

### CODE REVIEW

**Comment by prodsecmachine** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Licenses| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/74d72655-09dd-4d20-843f-753210022b23/license?refs=dd0e4b65382bd2f8235ef7f224178d357d09d296&source=prChecksComment) |
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/74d72655-09dd-4d20-843f-753210022b23?refs=dd0e4b65382bd2f8235ef7f224178d357d09d296&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Comment by naemono** [comment]
buildkite test this

**Comment by pebrc** [comment]
On 8.13.0 I ran into:
```
 Error: fail to read action store '/usr/share/elastic-agent/state/data/action_store.yml': yaml: input error: fail to decode bytes: cipher: message authentication failed         
```
Also, we need to verify that advanced configuration still works.

**Comment by pebrc** [comment]
Another issue 9.1.2 when upgrading from ECK 3.1. to this PR:
```
│ Error: fail to read state store '/usr/share/elastic-agent/state/data/state.enc': failed migrating YAML store JSON store: could not parse YAML                                                                                                                                                                             │
│ fail to decode bytes: cipher: message authentication failed    
```

File: pkg/controller/agent/pod.go [hunk 1]
```diff
@@ -148,6 +148,8 @@ func buildPodTemplate(params Params, fleetCerts *certificates.CertificatesSecret
 		if builder, err = amendBuilderForFleetMode(params, fleetCerts, fleetToken, builder, configHash); err != nil {
 			return corev1.PodTemplateSpec{}, err
 		}
+		// Point agent to static config file mounted from a secret to /etc/agent/elastic-agent.yml
+		builder = builder.WithArgs("-e", "-c", path.Join(ConfigMountPath, ConfigFileName))
```
Comment (pebrc) [inline pkg/controller/agent/pod.go:152]:
```diff
diff --git a/pkg/controller/agent/pod.go b/pkg/controller/agent/pod.go
index 13e53078d..9ee674e73 100644
--- a/pkg/controller/agent/pod.go
+++ b/pkg/controller/agent/pod.go
@@ -450,7 +450,7 @@ if [[ -f %[1]s ]]; then
     %[5]s
   fi
 fi
-/usr/bin/tini -- /usr/local/bin/docker-entrypoint -e
+/usr/bin/tini -- /usr/local/bin/docker-entrypoint -e "$@"
 `, caPath, ubiSharedCAPath, ubiUpdateCmd, debianSharedCAPath, debianUpdateCmd)
 }
```
We need to make sure the arguments added here are actually propagated to the command.

Thanks to @pkoutsovasilis for helping me debug this.

**Comment by pebrc** [comment]
The errors I hightlighted above are all coming from the migration from the status quo in 3.1 where `CONFIG_PATH` is `/etc/agent` to the new `CONFIG_PATH`. Because agent stores information needed to decrypt its state in the CONFIG_PATH this is lost on the migration (or on any container restart I guess) 

The guidance from @pkoutsovasilis is to force re-enroll with `FLEET_FORCE=true` ~develop a migration process that on the first attempt deletes `fleet.enc` and `fleet.enc.lock` from the state path. We need tracking for the migration (it should only be applied once when migrating from 3.1. to 3.2 or greater). I am wondering if we could use a marker file in the state path to track this and rely on a shell script. An alternative would be an annotation on the pod itself.~ 

```sh
if [[ ! -f "/usr/share/elastic-agent/state/eck.config_migrated" ]]; then
  echo "Attempting to remove fleet.enc and fleet.enc.lock from state path (ignore if not present)"
  rm -f "/usr/share/elastic-agent/state/fleet.enc" "/usr/share/elastic-agent/state/fleet.enc.lock" 2>/dev/null || true
  echo "Creating eck.config_migrated marker"
  touch "/usr/share/elastic-agent/state/eck.config_migrated"
fi
```

~What I don't know yet is how we detect the condition, that we actually need to delete these files. Ideally this should only happen when migrating from 3.1. to >=3.2~

**Update:** I am suspecting the migration is only necessary if a user went back and forth between `CONFIG_PATH=/etc/agent` and `CONFIG_PATH=STATE_PATH` as I did during testing. So I think we could maybe provide this proactively to support in case uses switch back and forth between ECK versions and run into this. But we do not need to add this to the ECK orchestration logic.

**Comment by naemono** [comment]
8.13 fleet-mode is throwing errors with this setup, specifically with the fleet-server agent:
```
Error: preparing STATE_PATH(/usr/share/elastic-agent/state) failed: mkdir /usr/share/elastic-agent/state/data: permission denied
```
Didn't investigate the issue as of yet...

7.17, 8.18, 9.x fleet-mode doesn't have the issue...

**Comment by naemono** [comment]
Testing advanced (9.2.0-snap) doesn't seem to work:
```
[root@gke-mmontgomery-dev-clus-default-pool-dbf006f3-xyov elastic-agent]# elastic-agent inspect | grep add_resource_metadata
[root@gke-mmontgomery-dev-clus-default-pool-dbf006f3-xyov elastic-agent]#
```

is this what you wanted applied @pebrc ? I'm not terribly familiar with this advanced config... 
```
❯ kc get agent -n elastic-stack  eck-stack-eck-agent -o yaml | yq '.spec.config'
providers.kubernetes:
  add_resource_metadata:
    deployment: true
```

**Comment by pebrc** [comment]
> Testing advanced (9.2.0-snap) doesn't seem to work:

I think you are right. The implementation from this PR seems to break advanced config mode.
Only if I manually delete `rm state/elastic-agent.yml` and restart the agent will it pick up the advanced config specified with the `-c` flag. This sounds like a bug to me. cc @pkoutsovasilis 

The previous implementation shipped with 3.1 declared `/etc/agent` to be the config directory, so anything we put there was automatically picked up.

**Comment by pebrc** [comment]
After speaking with @pkoutsovasilis the relevant code on agent is https://github.com/elastic/elastic-agent/blob/6186951dfbad2a7e0e1a37c26097d5b4d9d38dba/internal/pkg/agent/cmd/container.go#L853-L858 It seems there is a bug in that this code only checks if the file is there but does not actually take contents into account. 

We could look into an init container that removes the file if it exists to force agent to copy it again.

**Comment by pebrc** [comment]
> We could look into an init container that removes the file if it exists to force agent to copy it again.

This might not be necessary after all. It seems that `elastic-agent inspect` is not a reliable way to check the configured providers. We need to probably test against the actually ingested data to see if it works.

**Review by pebrc — APPROVED** [review]
LGTM I did extensive testing on this one.  @rhr323 we need a known issue entry for this one. If users downgrade to 3.1 or before and upgrade again to 3.2 they might run into errors like 
```
│ Error: fail to read state store '/usr/share/elastic-agent/state/data/state.enc': failed migrating YAML store JSON store: could not parse YAML                                                                                                                                                                             │
│ fail to decode bytes: cipher: message authentication failed    
```
or 
```
 Error: fail to read action store '/usr/share/elastic-agent/state/data/action_store.yml': yaml: input error: fail to decode bytes: cipher: message authentication failed         
```
in these cases they should add the `FLEET_FORCE=true` environment variable to their manifest to force agent to enrol anew (it can be removed once the agent has re-enroled)

**Comment by rhr323** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3.2|[](https://github.com/elastic/cloud-on-k8s/pull/8859)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
