### PR TITLE
Generate an event on sset spec change failure

### LINKED ISSUE #1871: Warn users when they attempt to change persistent disk size
As the validation webhook is currently non-operational, any attempts by the users to change the size of a persistent volume claim will fail silently. We should find a way to make this failure visible to the users.

**Way to reproduce:**

Create a cluster

```shell
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.4.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data 
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
EOF
```

Update the volume claim template

```shell
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.4.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data 
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
EOF
```

### PR DESCRIPTION
**Pull request by charith-elastic**
Generates an event if a sset spec change cannot be applied (e.g., attempting to change the size of a volume claim template). Even though we have a validation check for PVC modification, it does not catch this issue because the manual validation check in the internal reconciliation loop always sets the `Current` spec to `nil` and the check requires both `Current` and `Proposed` to be non-nil in order to work.

```
 Type     Reason               Age                    From                      Message
  ----     ------               ----                   ----                      -------
  Warning  ReconciliationError  1s (x8 over 12s)       elasticsearch-controller  Failed to apply spec change: StatefulSet.apps "quickstart-es-default" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

This is probably not the ideal way to handle this. It just avoids a large refactoring so close to a release. Long term, this should be revisited as part of #1811. 

Fixes #1871

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -164,6 +164,20 @@ go-run:
 				--operator-namespace=default --namespace= \
 				--auto-install-webhooks=false
 
+go-debug:
+	@(cd cmd &&	AUTO_PORT_FORWARD=true dlv debug \
```
Comment (thbkrkr) [inline Makefile]: Was it intentional to add this? (I'm not against it).
Is it mandatory to run `dlv debug` from the `cmd/` directory or `dlv debug ./cmd/main.go manager` could work?
Then, I wonder if we should put `go run` in a variable to make it possible to replace it by `dlv debug`.

Comment (charith-elastic) [reply Makefile]: If Delve is not run in the same directory as `main` it requires the package to be specified. Unfortunately, it seems to have problems parsing both `./cmd` and `github.com/elastic/cloud-on-k8s/cmd` apparently because we don't have any Go files at the package root. I didn't spend too much time on understanding why but I am going to do so later.

Unfortunately, the command execution is slightly different between `go-debug` and `go-run` so there's no straightforward way to reuse the targets either.

File: pkg/controller/elasticsearch/driver/nodes.go [hunk 2]
```diff
@@ -66,6 +70,7 @@ func (d *defaultDriver) reconcileNodeSpecs(
 	}
 	actualStatefulSets, err = HandleUpscaleAndSpecChanges(upscaleCtx, actualStatefulSets, expectedResources)
 	if err != nil {
+		reconcileState.AddEvent(corev1.EventTypeWarning, events.EventReconciliationError, fmt.Sprintf("Failed to apply spec change: %v", err))
```
Comment (sebgl) [inline pkg/controller/elasticsearch/driver/nodes.go]: This will also catch errors such as:
- cannot update the ES config
- cannot request ELasticsearch to grab the number of master nodes
- cannot reconcile the sset service

I'm wondering whether we should explicitly compare actual vs. expected VolumeClaimTemplates in the code and emit event + log at that time only. Maybe in a longer-term, fine with keeping this as a short-term solution.
