### PR TITLE
Perform forced rolling upgrade even if ES is reachable

### LINKED ISSUE #1847: API failure prevents cluster upgrade
This is a follow-up of #1827 

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.3.0
  nodes:
  - name: default
    podTemplate:
      spec:
        nodeSelector:
          diskType: mybad
    nodeCount: 1
  - name: default-2
    nodeCount: 1
```

With the manifest above [ES is considered as "reachable"](https://github.com/elastic/cloud-on-k8s/blob/ca2c732bd1ca9503a203b3902badafeb0a8aed5b/pkg/controller/elasticsearch/services/services.go#L65)  (i.e.`esReachable` is `true`) because there is at least one node in the service.
The problem is that [the subsequent call to the API fail](https://github.com/elastic/cloud-on-k8s/blob/master/pkg/controller/elasticsearch/driver/nodes.go#L78-L83) and do not give a chance to the deployment to be updated.

### PR DESCRIPTION
**Pull request by sebgl**
There are cases where Elasticsearch is reachable
(some Pods are Ready), but cannot respond to any requests.
For example, if there is 1/2 master nodes available. See
#1847. In such case,
the bootlooping/pending 2nd master node will stay stuck forever since we
will never reach the force upgrade part of the reconciliation.

This commit fixes it by running force upgrades (if required) right after
the upscale/spec change phase. This force upgrade phase becomes the new
"Step 2". Following steps (downscale and regular upgrade) require the
Elasticsearch cluster to be reachable.

Due to how this force rolling upgrade deletes some pods and set some
expectations, I chose to requeue immediately if it was attempted. This
way we don't continue the reconciliation based on a transient state
that would require us re-checking expectations. The next reconciliation
can be a "regular" one.

I think this also tends to simplify a bit the general logic: we first do
everything that does not require the ES API (steps 1 and 2), then move
on with downscales and standard rolling upgrades if ES is reachable
(steps 3 and 4); instead of passing an `esReachable` bool around.

The PR also modifies the existing force upgrade E2E test so that it covers
the case where Elasticsearch can be reached, but responds with 503.
The new version of the test does not pass with the master branch, but
does pass with this branch.

Fixes #1847.

### CODE REVIEW

File: pkg/controller/elasticsearch/driver/upgrade_forced.go [hunk 1]
```diff
@@ -11,13 +11,27 @@ import (
 
 	"github.com/elastic/cloud-on-k8s/pkg/apis/elasticsearch/v1beta1"
 	"github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/label"
+	"github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/sset"
 	"github.com/elastic/cloud-on-k8s/pkg/utils/k8s"
 )
 
-// maybeForceUpgrade may attempt a forced upgrade of all podsToUpgrade if allowed to,
+func (d *defaultDriver) MaybeForceUpgrade(statefulSets sset.StatefulSetList) (bool, error) {
```
Comment (thbkrkr) [inline pkg/controller/elasticsearch/driver/upgrade_forced.go]: `s|MaybeForceUpgrade|MayeTheForceBeWithYou|`? :grin:
