### PR TITLE
Use synchronous calls to get the Shards

### LINKED ISSUE #1750: TestMutationLessNodes is flaky
```
12:24:01      --- FAIL: TestMutationLessNodes/ES_cluster_health_should_eventually_be_green#01 (300.00s)
12:24:01          require.go:794: 
12:24:01              	Error Trace:	utils.go:80
12:24:01              	Error:      	Received unexpected error:
12:24:01              	            	health is red
12:24:01              	Test:       	TestMutationLessNodes/ES_cluster_health_should_eventually_be_green#01
```

I'm not sure what's going on here. This test is supposed to test a downscale from 3 to 1 master.
I think it happened once on my workstation: 

```
data-integrity-check 1 p STARTED    4 3.5kb 10.233.65.17 test-mutation-less-nodes-6snf-es-masterdata-0
data-integrity-check 2 p UNASSIGNED
data-integrity-check 0 p STARTED    0  283b 10.233.65.17 test-mutation-less-nodes-6snf-es-masterdata-0
```

```
curl -k -u elastic:$PASSWORD https://localhost:9200/_cluster/allocation/explain\?pretty
{
  "index" : "data-integrity-check",
  "shard" : 2,
  "primary" : true,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "NODE_LEFT",
    "at" : "2019-09-18T08:59:21.568Z",
    "details" : "node_left [DUsKggcYQ9Gy-gyrfkIflA]",
    "last_allocation_status" : "no_valid_shard_copy"
  },
  "can_allocate" : "no_valid_shard_copy",
  "allocate_explanation" : "cannot allocate because all found copies of the shard are either stale or corrupt",
  "node_allocation_decisions" : [
    {
      "node_id" : "EzWbSghXTvObgJtlPRXu_Q",
      "node_name" : "test-mutation-less-nodes-6snf-es-masterdata-0",
      "transport_address" : "10.233.65.17:9300",
      "node_attributes" : {
        "ml.machine_memory" : "2147483648",
        "xpack.installed" : "true",
        "ml.max_open_jobs" : "20"
      },
      "node_decision" : "no",
      "store" : {
        "in_sync" : false,
        "allocation_id" : "kKGUEcpNTGucBURVH5gKYQ"
      }
    }
  ]
}
```

I have run this test a lot of time locally but I never managed to reproduce it more than one time.

### PR DESCRIPTION
**Pull request by barkbay**
This PR introduces synchronous calls when fetching the shards in a cluster and get rid of API calls to cluster state.

I chose to not reuse ESState, the idea is to be sure to minimize the time between the different API calls:
1. Exclude the node(s)
2. Get the shards (synchronously)
3. Check if a node can be removed or delete for an upgrade
4. Scale down the cluster or delete the Pods

Note the following side effects:
* The current master node is not updated in the cluster status, I'm not sure this is a big loss ?
* Cluster info is added  in the observer in order to retrieve the cluster UUID

fix #1750 #1692

### CODE REVIEW

File: pkg/controller/elasticsearch/client/model.go [hunk 1]
```diff
@@ -104,97 +103,35 @@ type ClusterStateNode struct {
...
-	ClusterUUID  string                      `json:"cluster_uuid"`
-	Version      int                         `json:"version"`
-	MasterNode   string                      `json:"master_node"`
-	Nodes        map[string]ClusterStateNode `json:"nodes"`
-	RoutingTable RoutingTable                `json:"routing_table"`
+// Shard partially models Elasticsearch cluster shard.
+type Shard struct {
+	Index  string `json:"index"`
+	Shard  string `json:"shard"`
+	Prirep string `json:"prirep"`
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/client/model.go]: Nit: going by the docs prirep and state have known values, so it might be worthwhile to make these more specific types: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html

File: pkg/controller/elasticsearch/client/model.go [hunk 2]
```diff
@@ -104,97 +103,35 @@ type ClusterStateNode struct {
...
-			for _, shard := range shards {
-				if len(shard.Node) == 0 {
-					continue
-				}
-				// shard.Node is the id of the node, get the corresponding node name
-				nodeName := cs.Nodes[shard.Node].Name
-				result[nodeName] = append(result[nodeName], shard)
-			}
+	for _, shard := range s {
+		if len(shard.Node) > 0 {
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/client/model.go]: Does this happen when shards are unassigned? I wonder if dropping them is the right decision, rather adding them to the `""` key's values.

File: pkg/controller/elasticsearch/client/model.go [hunk 3]
```diff
@@ -104,97 +103,35 @@ type ClusterStateNode struct {
...
-			}
-		}
-	}
-	return result
-}
-
 // GetShardsByNode returns shards by node.
 // The result is a map with the name of the nodes as keys and the list of shards on the nodes as values.
-func (cs ClusterState) GetShardsByNode() map[string][]Shard {
+func (s Shards) GetShardsByNode() map[string][]Shard {
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/client/model.go]: nit: these can be map[string]Shards now right?

File: pkg/controller/elasticsearch/client/shard.go [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+type AllocationSetter interface {
+	ExcludeFromShardAllocation(nodes string) error
+}
+
+// ShardLister captures Elasticsearch API calls around shards retrieval.
+type ShardLister interface {
+	GetShards() (Shards, error)
+}
+
+type clientWrapper struct {
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/client/shard.go]: Can you help me understand why we need the wrapper?

File: pkg/controller/elasticsearch/driver/downscale.go [hunk 5]
```diff
@@ -86,11 +86,11 @@ func calculateDownscales(expectedStatefulSets sset.StatefulSetList, actualStatef
 
 // scheduleDataMigrations requests Elasticsearch to migrate data away from leavingNodes.
 // If leavingNodes is empty, it clears any existing settings.
-func scheduleDataMigrations(esClient esclient.Client, leavingNodes []string) error {
+func scheduleDataMigrations(allocationSetter esclient.AllocationSetter, leavingNodes []string) error {
 	if len(leavingNodes) != 0 {
 		log.V(1).Info("Migrating data away from nodes", "nodes", leavingNodes)
 	}
-	return migration.MigrateData(esClient, leavingNodes)
+	return migration.MigrateData(allocationSetter, leavingNodes)
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/driver/downscale.go]: I realize this isn't part of your change, but I wonder if we still want to keep this func around since it is essentially just a wrapper for `migration.MigrateData`

File: pkg/controller/elasticsearch/driver/downscale.go [hunk 6]
```diff
@@ -162,19 +165,24 @@ func calculatePerformableDownscale(
...
 		}
-		if migration.IsMigratingData(ctx.observedState, node, allLeavingNodes) {
+		if migrating {
 			ssetLogger(downscale.statefulSet).V(1).Info("Data migration not over yet, skipping node deletion", "node", node)
 			ctx.reconcileState.UpdateElasticsearchMigrating(ctx.resourcesState, ctx.observedState)
 			// no need to check other nodes since we remove them in order and this one isn't ready anyway
-			return performableDownscale
+			return performableDownscale, nil
 		}
+		ssetLogger(downscale.statefulSet).Info("Data migration is over, go for node deletion", "node", node)
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/driver/downscale.go]:
```suggestion
		ssetLogger(downscale.statefulSet).Info("Data migration completed successfully, starting node deletion", "node", node)
```

File: pkg/controller/elasticsearch/observer/state.go [hunk 7]
```diff
@@ -28,19 +27,18 @@ type State struct {
...
 	licenseChan := make(chan *client.License)
 
 	go func() {
-		clusterState, err := esClient.GetClusterState(ctx)
+		info, err := esClient.GetClusterInfo(ctx)
 		if err != nil {
-			// This is expected to happen from time to time
-			log.V(1).Info("Unable to retrieve cluster state", "error", err, "namespace", cluster.Namespace, "es_name", cluster.Name)
-			clusterStateChan <- nil
+			log.V(1).Info("Unable to retrieve cluster info", "error", err, "namespace", cluster.Namespace, "es_name", cluster.Name)
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/observer/state.go]: Is this still expected since we changed the endpoint or should we switch this to an error?

File: pkg/controller/elasticsearch/observer/state.go [hunk 8]
```diff
@@ -28,19 +27,18 @@ type State struct {
 // RetrieveState returns the current Elasticsearch cluster state
 func RetrieveState(ctx context.Context, cluster types.NamespacedName, esClient esclient.Client) State {
 	// retrieve both cluster state and health in parallel
```
Comment (anyasabo) [inline pkg/controller/elasticsearch/observer/state.go]:
```suggestion
	// retrieve both shard info and health in parallel
```

File: pkg/controller/elasticsearch/observer/state.go (hunk 7 above)
Comment (anyasabo) [inline pkg/controller/elasticsearch/observer/state.go]: Is this still expected since we changed the endpoint to just `/` rather than the cluster state?

**Comment by anyasabo** [comment]
Just nits and minor questions, looks mostly straightforward so I'm good once merge conflicts are fixed

File: pkg/controller/elasticsearch/client/model.go [hunk 9]
```diff
@@ -104,97 +103,35 @@ type ClusterStateNode struct {
...
-	Nodes        map[string]ClusterStateNode `json:"nodes"`
-	RoutingTable RoutingTable                `json:"routing_table"`
+// Shard partially models Elasticsearch cluster shard.
+type Shard struct {
+	Index  string `json:"index"`
+	Shard  string `json:"shard"`
+	Prirep string `json:"prirep"`
+	State  string `json:"state"`
+	// Node is the node name not the Node id
+	Node string `json:"node"`
```
Comment (david-kow) [inline pkg/controller/elasticsearch/client/model.go]: Call it NodeName?

File: pkg/controller/elasticsearch/client/model.go (hunk 2 above)
Comment (barkbay) [reply pkg/controller/elasticsearch/client/model.go]: They would not be used, not sure if it's worth it to change this in this PR.
But your point is interesting: should we take care of `UNASSIGNED` shards ?

File: pkg/controller/elasticsearch/observer/state.go (hunk 7 above)
Comment (barkbay) [reply pkg/controller/elasticsearch/observer/state.go]: As long as something can go wrong when this request is done I would say yes

File: pkg/controller/elasticsearch/client/shard.go (hunk 4 above)
Comment (barkbay) [reply pkg/controller/elasticsearch/client/shard.go]: Because I need an object to implement the high-level interfaces _(that being said, as I still feel new to Go maybe I'm missing the obvious :wink: )_

**Comment by barkbay** [comment]
jenkins test this please

File: pkg/controller/elasticsearch/client/model.go (hunk 2 above)
Comment (thbkrkr) [reply pkg/controller/elasticsearch/client/model.go]: It could be good to add a comment to not forget that `UNASSIGNED` shards are ignored because they have no node?

File: pkg/controller/elasticsearch/driver/testdata/shards.json [hunk 10]
```diff
@@ -0,0 +1,37 @@
+[{
```
Comment (thbkrkr) [inline pkg/controller/elasticsearch/driver/testdata/shards.json]: Nit: the first JSON object is not indented like the others.

File: pkg/controller/elasticsearch/observer/state.go (hunk 7 above)
Comment (anyasabo) [reply pkg/controller/elasticsearch/observer/state.go]: Sorry I wasn't clear. I think that was a justification for logging it as debug rather than an error, so I meant more should we change it to an error if it is now less common

File: pkg/controller/elasticsearch/client/shard.go (hunk 4 above)
Comment (anyasabo) [reply pkg/controller/elasticsearch/client/shard.go]: Since we are wrapping a struct in the same package I wasn't sure if it made sense to just add those funcs to Client

Comment (barkbay) [reply pkg/controller/elasticsearch/client/shard.go]: My idea was to have something easy to mock, bring an abstraction over the current HTTP client without introducing some additional complexity to it.

File: pkg/controller/elasticsearch/observer/state.go (hunk 7 above)
Comment (barkbay) [reply pkg/controller/elasticsearch/observer/state.go]: No worries 😄 
tbh I'm not sure I have the right answer, but as it seems that the observer will have less and less responsibilities in the operator I would be inclined to keep it at the debug level.

File: pkg/controller/elasticsearch/client/model.go [hunk 11]
```diff
@@ -104,97 +105,34 @@ type ClusterStateNode struct {
...
-	Version      int                         `json:"version"`
-	MasterNode   string                      `json:"master_node"`
-	Nodes        map[string]ClusterStateNode `json:"nodes"`
-	RoutingTable RoutingTable                `json:"routing_table"`
+// Shard partially models Elasticsearch cluster shard.
+type Shard struct {
+	Index    string     `json:"index"`
+	Shard    string     `json:"shard"`
+	State    ShardState `json:"state"`
+	NodeName string     `json:"node"`
```
Comment (david-kow) [inline pkg/controller/elasticsearch/client/model.go]: We probably want the tag to be `nodeName` too.

Comment (barkbay) [reply pkg/controller/elasticsearch/client/model.go]: `node` is the name of the element returned by `_cat/shards`: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html

Comment (david-kow) [reply pkg/controller/elasticsearch/client/model.go]: Ah, interesting. Ok.

File: pkg/controller/elasticsearch/client/shard.go (hunk 4 above)
Comment (barkbay) [reply pkg/controller/elasticsearch/client/shard.go]: 👍 , I will update this part with a new PR
