### PR TITLE
Move desired nodes version gate in the client

### LINKED ISSUE #7664: Reconciler error - elasticsearch client failed - [update_desired_nodes_request] failed to parse field [nodes]
After upgrading ECK 2.12.0, upgrading Elasticsearch from 8.12.2 to 8.13.0 is stalled on the following error:
```go
2024-03-27T11:48:26.479+0100    ERROR   manager.eck-operator    Reconciler error        {
  "service.version": "2.12.0-SNAPSHOT+dbdcc1c5", 
  "controller": "elasticsearch-controller", 
  "object": {"name":"q","namespace":"test"}, "namespace": "test", "name": "q", 
  "reconcileID": "f7ab9df2-ab31-4a34-b07e-c0c56c36e5f0", 
  "error": "elasticsearch client failed for https://q-es-internal-http.test.svc:9200/_internal/desired_nodes/4859b6c6-4d16-41a2-a59b-563dcb9cf34c/3?error_trace=true: 
  400 Bad Request: {Status:400 Error:{CausedBy:{Reason:Required [node_version] Type:illegal_argument_exception}
  Reason:[1:1387] [update_desired_nodes_request] failed to parse field [nodes] Type:x_content_parse_exception
  StackTrace:org.elasticsearch.xcontent.XContentParseException: [1:1387] [update_desired_nodes_request] failed to parse field [nodes]
...
```

### PR DESCRIPTION
**Pull request by thbkrkr**
This moves the version gate for removing the deprecated nodes field when using the desired nodes API in the es client,
so it uses the minimum version of Elasticsearch in the cluster instead of the Elasticsearch version in the Spec.

Resolves #7664.

### CODE REVIEW

**Review by pebrc — APPROVED** [review]

File: pkg/controller/elasticsearch/client/desired_nodes.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ type DesiredNode struct {
 	ProcessorsRange ProcessorsRange        `json:"processors_range"`
 	Memory          string                 `json:"memory"`
 	Storage         string                 `json:"storage"`
-	NodeVersion     string                 `json:"node_version,omitempty"` // deprecated in 8.13+
+	NodeVersion     string                 `json:"node_version"` // deprecated in 8.13+
```
Comment (thbkrkr) [inline pkg/controller/elasticsearch/client/desired_nodes.go:42]:
```suggestion
	NodeVersion     string                 `json:"node_version,omitempty"` // deprecated in 8.13+
```
