### PR TITLE
Fix readiness probe

### LINKED ISSUE #2248: Elasticsearch readiness probe might fail if a single node is stuck
It looks like we run `GET _cat/nodes?local` in order to check a pod's readiness:

https://github.com/elastic/cloud-on-k8s/blob/master/pkg/controller/elasticsearch/nodespec/readiness_probe.go#L32

This API call does two things: it gets a list of nodes from the local cluster state, and then it reaches out to all the nodes in the cluster and obtains some extra info from them. If a single node in the cluster fails to respond in this second step within a few seconds then I think this means we consider all the pods to be failing their readiness checks.

I think it's a bug to accept `?local` on this API at all given this gotcha (see https://github.com/elastic/elasticsearch/issues/50088) but also think we should be using a different API for our readiness checks. For instance, `GET _cluster/health?timeout=0s` returns `200 OK` iff the node is part of a cluster with a master, and `GET /` returns (something) if the node is actually alive and responding.

(I say "something" because in certain versions `GET /` return `503 Service Unavailable` if there is no master, but more recent versions always return `200 OK` here).

### PR DESCRIPTION
**Pull request by barkbay**
Fix #2248 

This PR updates the readiness probe by:
* Calling the root of the web server /
* Expecting a 200 response code unless Elasticsearch version is 6.x in which case 503 errors are tolerated

### CODE REVIEW

File: pkg/controller/elasticsearch/nodespec/readiness_probe.go [hunk 1]
```diff
@@ -28,7 +28,25 @@ func NewReadinessProbe() *corev1.Probe {
 
 const ReadinessProbeScriptConfigKey = "readiness-probe-script.sh"
 const ReadinessProbeScript = `#!/usr/bin/env bash
-# Consider a node to be healthy if it responds to a simple GET on "/_cat/nodes?local"
+
+# fail should be called as a last resort to help the user to understand why the probe failed
+function fail {
+  timestamp=$(date --iso-8601=seconds)
+  echo "{\"timestamp\": \"${timestamp}\", \"message\": \"readiness probe failed\", "$1"}" | tee /proc/1/fd/1
```
Comment (pebrc) [inline pkg/controller/elasticsearch/nodespec/readiness_probe.go]: That's clever :-) But should it be `/fd/2` for stderr?

File: pkg/controller/common/volume/downward_api.go [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+			},
+		},
+	},
+}
+
+var downwardApiVolumeMount = corev1.VolumeMount{
+	Name:      volume.DownwardApiVolumeName,
+	MountPath: volume.DownwardApiMountPath,
+	ReadOnly:  true,
+}
```
Comment (charith-elastic) [inline pkg/controller/common/volume/downward_api.go]: Nit: I feel like these don't need to be global variables (even though they're only package-private).  Maybe they can be directly returned from the method calls of the `DownwardApi` object?

File: pkg/controller/common/volume/downward_api.go [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+type DownwardApi struct{}
```
Comment (charith-elastic) [inline pkg/controller/common/volume/downward_api.go]: Nit: I think the Go convention would be to call this `DownwardAPI`

File: pkg/controller/common/volume/downward_api.go (hunk 2 above)
Comment (barkbay) [reply pkg/controller/common/volume/downward_api.go]: The idea here is to avoid to recreate what must be a constant everytime a Pod spec is created. I understand that it may sound like a very tiny optimization though 😐

Comment (charith-elastic) [reply pkg/controller/common/volume/downward_api.go]: :+1:  I don't feel strongly about it. Happy to leave it as is.

File: pkg/controller/elasticsearch/nodespec/readiness_probe.go [hunk 4]
```diff
@@ -28,7 +28,25 @@ func NewReadinessProbe() *corev1.Probe {
...
+}
+
+labels="` + volume.DownwardAPIMountPath + "/" + volume.LabelsFile + `"
+
+if [[ ! -f "${labels}" ]]; then
+  fail "\"reason\": \"${labels} does not exist\""
+fi
+
+# get Elasticsearch version from the downward API
+version=$(grep "elasticsearch.k8s.elastic.co/version" ${labels} | cut -d '=' -f 2)
```
Comment (thbkrkr) [inline pkg/controller/elasticsearch/nodespec/readiness_probe.go]: Nit: could be safer to use the `VersionLabelName` constant:

https://github.com/elastic/cloud-on-k8s/blob/d212d415a0651066ad2f6fd506929c0e3fa976e8/pkg/controller/elasticsearch/label/label.go#L27
