### PR TITLE
HTTP: Add support for external CA

### LINKED ISSUE #1494: Kibana cannot connect to ES when using self signed certs that are not created by the operator itself
We run a cluster internal CA (that is using cert-manager) which can issue certificates for all kind of applications in the cluster incl. elasticsearch. This cluster internal CA uses a self signed root certificate.

We use this Issuer to issue certificates to elasticsearch which works just fine.
E.g:
_Remark_: The code snippets below are pulumi code written in TypeScript, but I believe it's understandable enough how that would look in raw yaml

```ts
 {
    apiVersion: 'certmanager.k8s.io/v1alpha1',
    kind: 'Certificate',
    metadata: {
      name: CERT_NAME,
      namespace: dataNamespace.metadata.name
    },
    spec: {
      secretName: CERT_NAME,
      issuerRef: {
        name: 'cluster-internal-ca',
        kind: 'ClusterIssuer'
      },
      dnsNames: dataNamespace.metadata.name.apply(ns => [
        `${ES_NAME}-es-http.${ns}.es.local`,
        `${ES_NAME}-es-http`,
        `${ES_NAME}-es-http.${ns}.svc`,
        `${ES_NAME}-es-http.${ns}`
      ]),
      organization: [`ElasticSearch ${context.inferredEnvironment}`]
    }
  }
```

```ts
    apiVersion: 'elasticsearch.k8s.elastic.co/v1alpha1',
    kind: 'Elasticsearch',
    metadata: {
      name: ES_NAME,
      namespace: dataNamespace.metadata.name
    },
    spec: {
      version: '7.2.0',
      http: {
        tls: {
          certificate: {
            secretName: CERT_NAME
          }
        }
      },
```

However when creating a Kibana instance with  
```ts
elasticsearchRef: {
        name: ES_NAME
     }
```

The kibana instance fails to get into healthy mode and eventually fails continuously with:

```
{"type":"log","@timestamp":"2019-08-07T03:55:51Z","tags":["warning","task_manager"],"pid":1,"message":"PollError No Living connections"}
{"type":"log","@timestamp":"2019-08-07T03:55:52Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://main-es-http.es-instances.svc:9200/"}
```

As far as I can see it kibana does not mount anywhere the `ca.crt` that is contained in the elasticsearch secret (named `CERT_NAME` above) and could be used to establish trust.

I also tried to setup a kibana without elasticsearchRef via the undocumented `elasticsearch` section of Kibana:
```ts
   elasticsearch: {
        certificateAuthorities: {
          secretName: CERT_NAME
        },
        url: 'https://main-es-http:9200/',
        auth: {
          inline: { username: 'elastic', password: 'elastic-user-password' }
        }
      },
```

but that fails with the same error.

**NOTE**: The ElasticSearch instance works fine. I can connect to it from other application or via port-forward as long as I import the `ca.crt` from our cluster internal CA (that root cert is also contained in the secret passed to the elasticsearch instance).

Last but not least I believe the `spec.elasticsearch.auth.secret` is defined incorrectly in the CRD since it expects an object instead of a string / name.
Also it should probably be called `secretName` to be consistent with other places.

### PR DESCRIPTION
**Pull request by barkbay**
Fix #1494

### CODE REVIEW

**Comment by thbkrkr** [comment]
retest this please

File: operators/pkg/controller/common/certificates/http/certificates_secret.go [hunk 1]
```diff
@@ -14,6 +16,19 @@ import (
 
 type CertificatesSecret v1.Secret
 
+// CaPem returns the certificate of the certificate authority.
+func (s CertificatesSecret) CaPem() []byte {
```
Comment (pebrc) [inline operators/pkg/controller/common/certificates/http/certificates_secret.go]: Naming: I believe this should be `CAPem`
