### PR TITLE
Remove plugins from prepare-fs script in init container

### LINKED ISSUE #620: Download plugins in parallel to speedup node bootstrap
So far we process plugins to install one by one, sequentially.
Running them in parallel would speed up the start. Warning we still have to detect if one of the plugin failed to install.

(Side-note: writing this in Go or any other language than Bash could improve our flexibility here)

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #620 

* removes plugins from prepare-fs script in init container
* install plugins instead mechanism described in #1022 or via custom images
* trying to figure out whether we should remove the volume mount as well
     * Answer is no, we want to keep all the volume mounts to make it easier for users to actually leverage the new init container behaviour

### CODE REVIEW

File: operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script.go [hunk 1]
```diff
@@ -98,7 +73,7 @@ var scriptTemplate = template.Must(template.New("").Parse(
 	#  Files persistence #
 	######################
 
-	# Persist the content of bin/, config/ and plugins/
+	# Persist the content of bin/ and config/
```
Comment (sebgl) [inline operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script.go]: I think we don't need to persist bin & config anymore, since was mostly done for additional plugins stuff that can get installed in there.

File: operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script.go [hunk 2]
```diff
@@ -98,7 +73,7 @@ var scriptTemplate = template.Must(template.New("").Parse(
 	#  Files persistence #
```
Comment (sebgl) [inline operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script.go]: `PLUGIN_BIN=$ES_DIR/bin/elasticsearch-plugin ` can also be removed?

File: operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script_test.go [hunk 3]
```diff
@@ -29,11 +28,8 @@ func TestRenderScriptTemplate(t *testing.T) {
 							Target: "/usr/share/elasticsearch/users"}}},
 			},
 			wantSubstr: []string{
-				"$PLUGIN_BIN install --batch repository-s3",
-				"$PLUGIN_BIN install --batch repository-gcs",
 				"mv /usr/share/elasticsearch/config/* /mnt/elastic-internal/elasticsearch-config-local/",
 				"mv /usr/share/elasticsearch/bin/* /mnt/elastic-internal/elasticsearch-bin-local/",
```
Comment (sebgl) [inline operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script_test.go]: I think we don't need these 2 anymore (see above)

Comment (pebrc) [reply operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script_test.go]: Actually I think I need to revert the last commit and restore the plugin mount again. Otherwise it will be really tricky for users to make this work correctly

Comment (sebgl) [reply operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script_test.go]: Hm you're right.
