### PR TITLE
fix: cleanup orphaned secret mounts when removed from StackConfigPolicy

### LINKED ISSUE #8921: Copied secrets from StackConfigPolicy are not cleaned up when removed from spec
### Description

When a StackConfigPolicy (SCP) references a secret via `secretMounts`, ECK copies that secret to the Elasticsearch namespace with the appropriate naming convention. However, when the StackConfigPolicy is updated to remove the secret reference, the copied secret remains and is not cleaned up.

### Steps to Reproduce

1. Create an Elasticsearch with the label `env: test`

1. Create the secret to be referenced inside the secretSources
```bash
kubectl create secret generic test --from-literal=test=test -n elastic-system -o yaml --save-config --dry-run=client | kubectl apply -f -
```

2. Create a StackConfigPolicy with a `secretSources` reference to a secret:
```yaml
apiVersion: stackconfigpolicy.k8s.elastic.co/v1alpha1
kind: StackConfigPolicy
metadata:
  name: test-stack-config-policy
  namespace: elastic-system
spec:
  resourceSelector:
    matchLabels:
      env: test
  elasticsearch:
    clusterSettings:
      indices.recovery.max_bytes_per_sec: "100mb"
    secretMounts:
      - secretName: test
        mountPath: /mnt/secret/test
```

2. Apply the SCP and verify that ECK copies the secret to the namespace of Elasticsearch

3. Update the StackConfigPolicy and remove `secretMounts`.

4. Observe that the previously copied secret still exists in the target namespace

### Expected Behaviour

When a secret reference is removed from the StackConfigPolicy's `secretMounts`, ECK should:
- Delete the corresponding copied secret
- Clean up any secrets that are no longer referenced by any StackConfigPolicy

### Actual Behaviour

The copied secret remains in the target namespace indefinitely, even after the reference is removed from the StackConfigPolicy.

https://github.com/user-attachments/assets/2ca25342-c342-4cb8-809b-8d9a92493b9f

### Environment

- **ECK Version**: v3.2.0

### PR DESCRIPTION
**Pull request by pkoutsovasilis**
## Summary

  Fixes cleanup of orphaned secret mounts when removed from StackConfigPolicy. When a policy's `secretMounts` configuration is updated to remove secret references,
  the copied secrets in the target Elasticsearch namespace are now automatically deleted.

  Fixes #8921

  ## Problem

  When a StackConfigPolicy removes a secret reference from its `secretMounts` configuration, the copied secret remains in the target Elasticsearch namespace indefinitely, leading to resource accumulation and potential confusion.

  ### Reproduction Steps (from issue #8921)
  1. Create an Elasticsearch instance labeled `env: test`
  2. Create a source secret in the elastic-system namespace
  3. Create a StackConfigPolicy that references this secret via `secretMounts`
  4. ECK copies the secret to the Elasticsearch namespace
  5. Update the StackConfigPolicy to remove the `secretMounts` section
  6. **Bug**: The copied secret persists in the Elasticsearch namespace indefinitely

  ### Expected Behavior
  When a secret reference is removed from a StackConfigPolicy's `secretMounts`, ECK should automatically delete the corresponding copied secret from the target namespace.

## Solution

  Added `cleanupOrphanedSecretMounts()` function that runs during policy reconciliation to:
  1. List all secrets in the ES namespace that are soft-owned by the policy
  2. Filter for secrets with the `policy.k8s.elastic.co/source-secret-name` annotation (identifies SecretMount-managed secrets)
  3. Compare against the current `secretMounts` list in the policy spec
  4. Delete secrets that are no longer referenced in the policy

### CODE REVIEW

**Comment by prodsecmachine** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/6ec04cbf-5d1f-4c5f-83cd-5609957c861a?refs=1884b60b4992bde097639e7954a23f6c384a66b6&source=prChecksComment) |
| :white_check_mark: | Licenses| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/elastic-cloud-on-k8s/pr-checks/6ec04cbf-5d1f-4c5f-83cd-5609957c861a/license?refs=1884b60b4992bde097639e7954a23f6c384a66b6&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

File: pkg/controller/stackconfigpolicy/elasticsearch_config_settings.go [hunk 1]
```diff
@@ -114,6 +120,53 @@ func reconcileSecretMounts(ctx context.Context, c k8s.Client, es esv1.Elasticsea
...
+	}
+
+	if err := c.List(ctx, &secrets, client.InNamespace(es.Namespace), matchLabels); err != nil {
+		return err
+	}
+
+	for i := range secrets.Items {
+		secret := &secrets.Items[i]
+
+		// Skip secrets that do not have a source secret annotation
```
Comment (pebrc) [inline pkg/controller/stackconfigpolicy/elasticsearch_config_settings.go]: Maybe amend the comment that this annotation identifies the secrets for the secret mounts?

**Review by pebrc — APPROVED** [review]

File: pkg/controller/stackconfigpolicy/elasticsearch_config_settings.go (hunk 1 above)
Comment (pkoutsovasilis) [reply pkg/controller/stackconfigpolicy/elasticsearch_config_settings.go]: amended in 1884b60b4992bde097639e7954a23f6c384a66b6

**Review by pebrc — APPROVED** [review]
