### PR TITLE
Re-bootstrap single master 7.x clusters when upgrading from 6.x

### LINKED ISSUE #1660: Upgrading 1 node from 6.X to 7.X fails since cluster appears already bootstrapped
Upgrading a 1-node cluster from 6.X to 7.X fails, because we don't set initial_master_nodes on that node, since we consider the cluster is already bootstrapped.

We annotate the cluster as "bootstrapped" with its UUID from the cluster state once observed by the observers. Then, we don't set zen2 initial master nodes anymore.

However when we migrate a 1-node cluster from 6.X to 7.X, there is no master node to join.

We should probably differentiate:
* cluster being bootstrapped in the sense "already exists" (concept used in https://github.com/elastic/cloud-on-k8s/pull/1654)
* cluster being bootstrapped for zen2 (has seen initial master nodes already)

Related comment in a PR: https://github.com/elastic/cloud-on-k8s/pull/1654#discussion_r318964828
Related discussion: https://github.com/elastic/cloud-on-k8s/issues/1281#issuecomment-524832319

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #1660 

When upgrading single master clusters from 6.x to 7.x we are effectively reconstructing the cluster.
The new 7.x node is not joining a new cluster as it would be the case for a rolling upgrade on an HA cluster,
but it rather needs to be bootstrapped again as if it were a new 7.x cluster.

We control bootstrap configuration via the cluster uuid annotation on the Elasticsearch CRD, this commit resets
that annotation on single master upgrades to 7.x thereby regenerating bootstrap configuration.

### CODE REVIEW

File: test/e2e/es/version_upgrade_test.go [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+	mutated := initial.WithNoESTopology().
+		WithVersion("7.2.0").
+		WithESMasterDataNodes(3, elasticsearch.DefaultResources)
+
+	RunESMutation(t, initial, mutated)
+}
+
+func TestVersionUpgradeSingle680To720(t *testing.T) {
+	initial := elasticsearch.NewBuilder("test-version-up-680-to-720").
```
Comment (thbkrkr) [inline test/e2e/es/version_upgrade_test.go]: Maybe name the test `test-version-up-1-680-to-720` (we can go up to 36-1-4=31 chars) so that the test names remain unique.

File: pkg/controller/elasticsearch/driver/bootstrap.go [hunk 2]
```diff
@@ -34,6 +48,28 @@ func ReconcileClusterUUID(c k8s.Client, cluster *v1alpha1.Elasticsearch, observe
 	return nil
 }
 
+func removeUUIDAnnotation(client k8s.Client, elasticsearch *v1alpha1.Elasticsearch) error {
+	annotatations := elasticsearch.Annotations
+	if annotatations == nil {
+		return nil
+
```
Comment (thbkrkr) [inline pkg/controller/elasticsearch/driver/bootstrap.go]: Unnecessary empty line.

File: pkg/controller/elasticsearch/driver/bootstrap.go [hunk 3]
```diff
@@ -34,6 +49,31 @@ func ReconcileClusterUUID(c k8s.Client, cluster *v1alpha1.Elasticsearch, observe
 	return nil
 }
 
+func removeUUIDAnnotation(client k8s.Client, elasticsearch *v1alpha1.Elasticsearch) error {
+	annotatations := elasticsearch.Annotations
```
Comment (thbkrkr) [inline pkg/controller/elasticsearch/driver/bootstrap.go]: s|annotatations|annotations|

File: pkg/controller/elasticsearch/driver/bootstrap.go [hunk 4]
```diff
@@ -34,6 +49,31 @@ func ReconcileClusterUUID(c k8s.Client, cluster *v1alpha1.Elasticsearch, observe
...
+
+// clusterNeedsReBootstrap is true if we are updating a single master cluster from 6.x to 7.x
+// because we lose the 'cluster' when rolling the single master node.
+// Invariant: no grow and shrink
+func clusterNeedsReBootstrap(client k8s.Client, es *v1alpha1.Elasticsearch) (bool, error) {
+	initialZen2Upgrade, err := zen2.IsInitialZen2Upgrade(client, *es)
+	if err != nil {
+		return false, err
+	}
+	var currentMasters []v1.Pod
```
Comment (thbkrkr) [inline pkg/controller/elasticsearch/driver/bootstrap.go]: `currentMasters` declaration could be omitted.

File: test/e2e/es/version_upgrade_test.go [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+	initial := elasticsearch.NewBuilder("test-version-up-1-710-to-720").
+		WithVersion("7.1.0").
+		WithESMasterDataNodes(1, elasticsearch.DefaultResources)
+
+	mutated := initial.WithNoESTopology().
+		WithVersion("7.2.0").
+		WithESMasterDataNodes(1, elasticsearch.DefaultResources)
+
+	RunESMutation(t, initial, mutated)
+}
```
Comment (thbkrkr) [inline test/e2e/es/version_upgrade_test.go]: Nit: we could try to optimize a bit the number of images used in the e2e tests. By using 7.3.0 instead of 7.2.0 will avoid to pull another version of the ES image. A downside is that it works until the Elastic stack version is 7.3.0. So we could use `test.Ctx().ElasticStackVersion` that should work until we are <=7.x. So maybe we're probably not at a few image pulls near.

Comment (pebrc) [reply test/e2e/es/version_upgrade_test.go]: Yes, these version upgrade tests need a little bit of re-think I believe and not only because of the images we pull. They are going against the grain of the whole test framework by hard coding the version in the test. That means they run redundantly n-times for each stack version we test and so forth.

File: pkg/controller/elasticsearch/driver/bootstrap.go [hunk 6]
```diff
@@ -23,6 +25,18 @@ func AnnotatedForBootstrap(cluster v1alpha1.Elasticsearch) bool {
 
 func ReconcileClusterUUID(c k8s.Client, cluster *v1alpha1.Elasticsearch, observedState observer.State) error {
 	if AnnotatedForBootstrap(*cluster) {
```
Comment (barkbay) [inline pkg/controller/elasticsearch/driver/bootstrap.go]: I think there's a possible race condition here:

- initial state: one 6.x bootstrapped master node
- loop n:
  - user request an upgrade to 7.2
  - `elasticsearch.k8s.elastic.co/cluster-uuid` is removed
  - spec is changed .... but K8S is lagging and the new master is not rolled out immediately 
- loop n+1:
  - 6.8 master is still there, uid is set again
  - 7.2 finally comes out, `uid` is set: no bootstrap 💥 

I guess a fix should be to always  check if the current master is out of sync with something like that:

```golang
	if clusterIsBootstrapped(observedState) && !reBootstrap {
		// cluster bootstrapped but not annotated yet
		return annotateWithUUID(cluster, observedState, c)
	}
```

_nit: An even more subtile race condition would be to have an upscale request right after `elasticsearch.k8s.elastic.co/cluster-uuid` is removed. All new master Pods would be added simultaneously, but I guess we are fine because Zen2 would be bootstrapping anyway._

Comment (pebrc) [reply pkg/controller/elasticsearch/driver/bootstrap.go]: Well spotted!

> An even more subtile race condition would be to have an upscale request right after elasticsearch.k8s.elastic.co/cluster-uuid is removed. All new master Pods would be added simultaneously, but I guess we are fine because Zen2 would be bootstrapping anyway.

Yes that would be fine because as soon as we have at least one other master still running when we roll out the 7.2 node it will bootstrap OK.
