### PR TITLE
Fix Kibana to terminate all pods before restarting during version change

### LINKED ISSUE #2049: Kibana does not support rolling upgrades
Kibana currently does not support rolling upgrades. 

The expected upgrade path for Kibana is to stop all Kibanas of the previous version, then start up the new version. We currently use a Deployment which does violate this invariant. 

https://www.elastic.co/guide/en/kibana/current/upgrade.html

Running into trouble with saved object migrations is only one effect of having multiple versions of Kibana running at the same time, see https://www.elastic.co/guide/en/kibana/current/upgrade-migrations.html

### PR DESCRIPTION
**Pull request by david-kow**
### Description
This PR fixes #2049. 
During version upgrade, all Kibana instances with old version have to be stopped before starting any instance with the new version. To do that, the operator will supply Recreate strategy to Kibana deployment when it detects that version upgrade is in progress. To avoid Kibana downtime for all other spec changes, RollingUpdate strategy will be used when version doesn't change. 

### Detection
Operator needs to be consistent throughout the entire upgrade process even if reconciliation loop is ran multiple times. To do that, operator looks at current spec and all the versions in existing Kibana pods. If the version is the same everywhere, the RollingUpdate strategy is used, otherwise Recreate strategy is used.

### Pod version
New label is introduced on Kibana pods. It contains the Kibana version that the pod is running. The need for a new label comes from the fact that there is no other source of truth available:
- Kibana spec has a version, but Pods will outlive any particular version of that spec, so it's not possible to trace back if the spec was updated
- Deployment has the same "outliving" issue as Kibana spec
- Both ReplicaSet and Pod currently have config checksum and container image. The former changes on every config change and as we care only about version changes it's not useful. The latter can be user provided and might not indicate the version in the name.

Given the above, `kibana.k8s.elastic.co/version` label was introduced. Both ReplicaSets and Pods have it, but it's being read from Pods.

### Upgrade case
When the operator version containing new label will be deployed in k8s cluster with already existing Kibana deployment, the version label will not be present. This means that the operator can't reason about the deployment strategy to use. Given that, we have two options for default behavior:
- use RollingUpdate strategy - better experience for users, but slight risk of data corruption/loss (when Kibana spec is updated while operator is not running),
- use Recreate strategy - Kibana will have downtime on operator upgrade, but there is no risk of data corruption/loss.

It seems to me we should aim for safety first hence I went with Recreate strategy by default. 

### Stale cache considerations
If our client cache is stale, the operator might not see the actual state, but outdated one. I think there is just one case where we won't get the expected behavior.

Actual version (version in cache):
```
spec  | pods
A (A) | A (A), A (A), A (A)
-> version upgrade from A to B
B (A) | A (A), A (A), A (A)
B (B) | A (A), A (A), A (A)
B (B) | B (A), B (A), B (A)
B (B) | B (B), B (B), B (A)
-> non-version config change
```

- spec version gets updated from A to B
- all pods get updated to B, but cache still contains a stale entry with Pod at version A
- another change to spec comes in. It's not related to version, but as we read the stale cache we consider that version upgrade is still in progress and we use Recreate strategy
- Kibana has downtime when it wasn't necessary

To avoid the issue above we inspect the number of replicasets for given deployment. If there is more then one and they have multiple versions we requeue and wait until it stabilizes, ie. all pods are owned by a single replicaset.

### CODE REVIEW

**Comment by david-kow** [comment]
I've realized that the approach to avoid stale cache issue causes a problem in the following sequence of events:
1. good Kibana spec running
2. spec gets updated to bad (bootlooping) config without changing version (v1)
3. spec get updated to good config with version change (v2)

The state after those steps is:
- spec at v2
- good replicaset1 at v1
- bad replicaset2 at v1

We'd have multiple versions and multiple replicasets, so the operator will keep on requeuing, but it will do so indefinitely because bad replicaset2 won't ever finish its rollout. In such a case user will need to first revert back to good config at v1 and then update to good config at v2.

There is a trade-off between the above and potential unnecessary downtime when we hit stale cache at the right time. Thoughts?

File: pkg/controller/kibana/driver.go [hunk 1]
```diff
@@ -87,7 +91,45 @@ func secretWatchFinalizer(kibana kbtype.Kibana, watches watches.DynamicWatches)
 	}
 }
 
-func (d *driver) deploymentParams(kb *kbtype.Kibana) (deployment.Params, error) {
+func (d *driver) getStrategyType(kb *kbtype.Kibana) (appsv1.DeploymentStrategyType, bool, error) {
```
Comment (pebrc) [inline pkg/controller/kibana/driver.go]: Maybe a comment explaining the return types specifically the meaning of `bool`. It is clear at the call site but without context harder to understand maybe.

File: pkg/controller/kibana/driver.go [hunk 2]
```diff
@@ -87,7 +91,45 @@ func secretWatchFinalizer(kibana kbtype.Kibana, watches watches.DynamicWatches)
...
+	differentVersionsDetected := false
+	owners := make(map[string]struct{})
+	for _, pod := range pods.Items {
+		if len(pod.OwnerReferences) != 1 {
+			return "", false, fmt.Errorf("pod %s has %d owners while expecting 1", pod.Name, len(pod.OwnerReferences))
+		}
+		owners[pod.OwnerReferences[0].Name] = struct{}{}
+
+		ver, ok := pod.Labels[label.KibanaVersionLabelName]
+		// if label is missing, we assume this is first pass of reconciliation that will populate
```
[the remark this answers is not in the document]
Comment (anyasabo) [reply pkg/controller/kibana/driver.go]: I think if this deployment was reconciled by an older version of the operator, correct? It might be worth calling out in a comment either way

[the remark this answers is not in the document]
Comment (david-kow) [reply pkg/controller/kibana/driver.go]: Yes, Anya is correct. Actually I intended the comment to call this out, but it seems I failed at that :) I'll reword it.

**Comment by david-kow** [comment]
@pebrc 
> Maybe you could somehow surface this condition in an event+log entry?
I think it's difficult - you could do it every time, but then some of the logs would be false positive (ie. we detected it being stuck, but it's not). Or we could track for how long this is happening, but this is also susceptible to errors, needs state, etc. 

> Another option would be to validate version upgrades by checking if there are any bootlooping pods in the Kibana and rejecting the upgrade if there are any
I think I agree this is hard. Especially for cases where we have config updates coming quickly, there might not be enough time to validate.

Given the impact/time needed for this work I think I'd do what @barkbay is proposing, ie. allow Kibana downtime in some cases when we have stale cache. WDYT?

**Comment by david-kow** [comment]
@pebrc Will do. As to the e2e tests, I don't think it's easily reproducible as it depends on cache timing.

**Comment by pebrc** [comment]
>  As to the e2e tests, I don't think it's easily reproducible as it depends on cache timing.

@david-kow true, but I guess we could have an e2e test that exercises regular updates and version upgrades in succession, which might or might not run into the suspect cache staleness, but is a good test to have anyway.

File: pkg/controller/common/deployment/reconcile.go [hunk 3]
```diff
@@ -28,6 +28,7 @@ type Params struct {
 	Labels          map[string]string
 	PodTemplateSpec corev1.PodTemplateSpec
 	Replicas        int32
+	Type            appsv1.DeploymentStrategyType
```
Comment (sebgl) [inline pkg/controller/common/deployment/reconcile.go]: I think `Strategy` may be more explicit than `Type` here?

File: pkg/controller/kibana/driver.go [hunk 4]
```diff
@@ -87,6 +89,28 @@ func secretWatchFinalizer(kibana kbtype.Kibana, watches watches.DynamicWatches)
 	}
 }
 
+// getStrategyType decides which deployment strategy (RollingUpdate or Recreate) to use based on whether the version
+// upgrade is in progress.
```
Comment (sebgl) [inline pkg/controller/kibana/driver.go]:
```
// Kibana does not support a smooth rolling upgrade from one version to another: running multiple versions
// simultaneously may lead to concurrency bugs and data corruption.
```

File: test/e2e/test/kibana/steps_mutation.go [hunk 5]
```diff
@@ -5,20 +5,73 @@
...
 
 func (b Builder) MutationTestSteps(k *test.K8sClient) test.StepList {
-	return b.UpgradeTestSteps(k).
+	return b.AnnotatePodsWithBuilderHash(k).
+		WithSteps(b.UpgradeTestSteps(k)).
 		WithSteps(b.CheckK8sTestSteps(k)).
 		WithSteps(b.CheckStackTestSteps(k))
 }
 
+func (b Builder) AnnotatePodsWithBuilderHash(k *test.K8sClient) test.StepList {
```
Comment (sebgl) [inline test/e2e/test/kibana/steps_mutation.go]: IIUC this is almost a duplicate from `AnnotatePodsWithBuilderHash` in the elasticsearch package. Except the way we list pods is different. Can we try to factor things together?

File: test/e2e/test/kibana/steps_mutation.go [hunk 6]
```diff
@@ -5,20 +5,72 @@
...
+					if err := k.Client.Update(&pod); err != nil {
+						// may error out with a conflict if concurrently updated by the operator,
+						// which is why we retry with `test.Eventually`
+						return err
+					}
+				}
+				return nil
+			}),
+		},
+		// make sure this is propagated to the local cache so next test steps can expect annotated pods
```
Comment (sebgl) [inline test/e2e/test/kibana/steps_mutation.go]: I think I wrote this for the elasticsearch side of things but it's probably useless: the k8s client we use in E2E tests does not rely on a cached reader. Which in the context of E2E tests makes sense, I think (the performance hit is fine?).
Could you double-check I am not mistaken here and remove this block (also on ES side) if it makes sense? 🙏

File: test/e2e/test/watcher.go [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+
+package test
+
+import (
+	"fmt"
+	"testing"
+	"time"
+)
+
+type Watcher struct {
```
Comment (sebgl) [inline test/e2e/test/watcher.go]: Can we refactor Elasticsearch `checks_budget.go` using this new `Watcher` mechanism? (I'm fine with doing that in another PR or just opening an issue).

File: test/e2e/test/kibana/steps_mutation.go (hunk 5 above)
Comment (sebgl) [reply test/e2e/test/kibana/steps_mutation.go]: Also I think it's fine to use the same `BuilderHashAnnotation` for both.

File: test/e2e/test/kibana/builder.go [hunk 8]
```diff
@@ -106,6 +107,21 @@ func (b Builder) WithResources(resources corev1.ResourceRequirements) Builder {
 	return b
 }
 
+func (b Builder) WithMutatedFrom(mutatedFrom *Builder) Builder {
```
Comment (sebgl) [inline test/e2e/test/kibana/builder.go]: The ES builder does not have this function, can you add it for consistency (or remove this one, up to you)?

File: test/e2e/kb/version_upgrade_test.go [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+				for _, pod := range pods {
+					if k8s.IsPodReady(pod) {
+						ready++
+					}
+				}
+				observations = append(observations, ready)
+			}
+		},
+		func(k *test.K8sClient, t *testing.T) {
+			assert.Contains(t, observations, 0)
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: I'm not sure I understand what this is doing. From what I read we check that, at least once, we observed 0 pods ready? I guess this would mean "we expect downtime". What if the watcher does not catch the downtime period? I know it's running every 1 sec but stil, sounds a bit arbitrary.

Another approach would be to store a list of all current Pods versions in one observation. Then at the end go through all observations and make sure there is no observation that contains 2 different versions. Meaning 2 different versions of Kibana where running at the same time. This is catching "never 2 different Kibana versions simultaneously" instead of "expect a downtime", which is closer to what we want, I think.

File: test/e2e/kb/version_upgrade_test.go [hunk 10]
```diff
@@ -0,0 +1,120 @@
...
+
+	test.RunMutationsWhileWatching(
+		t,
+		[]test.Builder{esBuilder, kbBuilder},
+		[]test.Builder{esBuilder, kbBuilder.WithVersion("7.4.1").WithMutatedFrom(&kbBuilder)},
+		[]test.Watcher{w},
+	)
+}
+
+func TestRespecAndVersionUpgrade(t *testing.T) {
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: Maybe more `TestVersionUpgradeAndRespec`

File: test/e2e/kb/version_upgrade_test.go [hunk 11]
```diff
@@ -0,0 +1,120 @@
...
+		WithESMasterDataNodes(1, elasticsearch.DefaultResources).
+		WithVersion("7.4.1")
+
+	kbBuilder1 := kibana.NewBuilder(name).
+		WithElasticsearchRef(esBuilder.Ref()).
+		WithNodeCount(3).
+		WithVersion("7.4.0")
+
+	kbBuilder2 := kbBuilder1.WithMutatedFrom(&kbBuilder1).WithVersion("7.4.1")
+	kbBuilder3 := kbBuilder2.WithMutatedFrom(&kbBuilder2).WithLabel("some", "label")
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: let's add a comment for this test:
```
Perform a Kibana version upgrade immediately followed by a Kibana configuration change.
We want to make sure our version upgrade requirements (a single version runnning at one time) still apply.
```

File: test/e2e/kb/version_upgrade_test.go [hunk 12]
```diff
@@ -0,0 +1,120 @@
...
+			}
+
+			hadZero = hadZero || ready == 0
+			if hadZero && ready > 0 {
+				shouldHaveNonZero = true
+			}
+
+			if shouldHaveNonZero && ready == 0 {
+				failed = true
+			}
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: same comment re checking downtime vs. checking multiple versions running in parallel.

File: test/e2e/test/kibana/steps_mutation.go (hunk 5 above)
Comment (david-kow) [reply test/e2e/test/kibana/steps_mutation.go]: It differs in listing pods, annotation name and hash generation which seems like the entire step. I can refactor if you feel strongly, but I didn't hence this way :)

File: test/e2e/kb/version_upgrade_test.go (hunk 10 above)
Comment (pebrc) [reply test/e2e/kb/version_upgrade_test.go]: What's a `respec` ?

File: test/e2e/test/watcher.go (hunk 7 above)
Comment (pebrc) [reply test/e2e/test/watcher.go]: Would the continuous health check in `steps_mutation.go` be another candidate for this?

Comment (david-kow) [reply test/e2e/test/watcher.go]: I hoped to do it in a different PR, filed https://github.com/elastic/cloud-on-k8s/issues/2174 to track.

File: test/e2e/kb/version_upgrade_test.go (hunk 9 above)
Comment (david-kow) [reply test/e2e/kb/version_upgrade_test.go]: I think both approaches are equivalent for all practical purposes, so I'll change it, but for the record, seeing downtime positively confirms there were no two same versions running. Not seeing two versions simultaneously confirms just that, that we didn't observe two versions running at the same time (but it's not implicating that it didn't happen).

File: test/e2e/kb/version_upgrade_test.go (hunk 11 above)
Comment (david-kow) [reply test/e2e/kb/version_upgrade_test.go]: This test's purpose is a bit different, but I've added a comment :)

File: test/e2e/kb/version_upgrade_test.go (hunk 12 above)
Comment (david-kow) [reply test/e2e/kb/version_upgrade_test.go]: This one is meant to check whether we don't do recreate twice, ie. whether after first upgrade, the label add change will result in a rolling upgrade. Checking for pods version doesn't achieve confirming that the rollout is rolling upgrade. 

In other words, if we hit a race condition/bug during second upgrade (label add) and the operator will use recreate again, the versions will be consistent, but since they were killed and started at the same time the pods won't be ready. Which is what I'd like to detect here.

File: test/e2e/test/kibana/steps_mutation.go (hunk 5 above)
Comment (david-kow) [reply test/e2e/test/kibana/steps_mutation.go]: Chatted offline, will fix 👍

File: test/e2e/kb/version_upgrade_test.go (hunk 12 above)
Comment (david-kow) [reply test/e2e/kb/version_upgrade_test.go]: Chatted offline, we will have both.

File: test/e2e/kb/version_upgrade_test.go (hunk 9 above)
Comment (david-kow) [reply test/e2e/kb/version_upgrade_test.go]: Chatted offline, we will have both.

File: test/e2e/kb/version_upgrade_test.go (hunk 10 above)
Comment (david-kow) [reply test/e2e/kb/version_upgrade_test.go]: @pebrc short for respecification, ie. updating the configuration :) I tried to distinguish between version change and all other changes. Would plain `update` be better?

File: test/e2e/kb/version_upgrade_test.go [hunk 13]
```diff
@@ -0,0 +1,137 @@
...
+
+	test.RunMutationsWhileWatching(
+		t,
+		[]test.Builder{esBuilder, kbBuilder1},
+		[]test.Builder{esBuilder, kbBuilder2, kbBuilder3},
+		[]test.Watcher{w, NewVersionWatcher(opts...)},
+	)
+}
+
+func NewReadinessWatcher(opts ...client.ListOption) test.Watcher {
```
Comment (pebrc) [inline test/e2e/kb/version_upgrade_test.go]: Maybe add a comment explaining the rationale, assumptions and invariants behind these two watchers

File: test/e2e/kb/version_upgrade_test.go [hunk 14]
```diff
@@ -0,0 +1,137 @@
...
+	var readinessObservations []int
+	return test.NewWatcher("watch pods versions", 1*time.Second,
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: `watch pods readiness: expect some downtime`

File: test/e2e/kb/version_upgrade_test.go [hunk 15]
```diff
@@ -0,0 +1,137 @@
...
+			}
+		},
+		func(k *test.K8sClient, t *testing.T) {
+			assert.Contains(t, readinessObservations, 0)
+		})
+}
+
+func NewVersionWatcher(opts ...client.ListOption) test.Watcher {
+	var podObservations [][]v1.Pod
+	return test.NewWatcher("watch pods versions", 1*time.Second,
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: `watch pods versions: should not observe multiples versions running at once`

File: test/e2e/kb/version_upgrade_test.go [hunk 16]
```diff
@@ -0,0 +1,137 @@
...
+		func(k *test.K8sClient, t *testing.T) {
+			if pods, err := k.GetPods(opts...); err != nil {
+				t.Logf("got error: %v", err)
```
Comment (sebgl) [inline test/e2e/kb/version_upgrade_test.go]: `t.Logf("failed to list pods: %v", err)`

File: test/e2e/test/builder.go [hunk 17]
```diff
@@ -4,6 +4,10 @@
 
 package test
 
+// BuilderHashAnnotation is the name of an annotation set by the E2E tests on Kibana resources
```
Comment (sebgl) [inline test/e2e/test/builder.go]: not only Kibana?

**Comment by david-kow** [comment]
Updated the description to reflect changes we agreed on in the comments.
